# Generated by Django 4.2.25 on 2026-01-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_active_company_alter_company_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NxPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMembershipPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_membership_permissions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companymembership')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.nxpermission')),
            ],
        ),
        migrations.AddField(
            model_name='companymembership',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='memberships', through='accounts.CompanyMembershipPermission', to='accounts.nxpermission'),
        ),
        migrations.AddConstraint(
            model_name='companymembershippermission',
            constraint=models.UniqueConstraint(fields=('membership', 'permission'), name='uniq_membership_permission'),
        ),
    ]
