# Generated by Django 4.2.25 on 2026-01-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nxpermission_companymembershippermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companymembership',
            options={'ordering': ['company', 'user']},
        ),
        migrations.AlterModelOptions(
            name='nxpermission',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='thousand_separator',
            field=models.CharField(blank=True, default=',', max_length=1),
        ),
    ]
