# Generated by Django 4.2.25 on 2026-01-13 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='nxpermission',
            options={'ordering': ['module', 'code'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='current_period',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='company',
            name='decimal_places',
        ),
        migrations.RemoveField(
            model_name='company',
            name='decimal_separator',
        ),
        migrations.RemoveField(
            model_name='company',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='company',
            name='thousand_separator',
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=100),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('accounts', 'Company').objects.all().update(slug=models.F('id')),
            reverse_code=migrations.RunPython.noop,
        ),
       
        
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nxpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nxpermission',
            name='default_for_roles',
            field=models.JSONField(blank=True, default=list, help_text="Roles that have this permission by default (e.g., ['OWNER', 'ADMIN'])"),
        ),
        migrations.AddField(
            model_name='nxpermission',
            name='module',
            field=models.CharField(default='general', help_text="Module this permission belongs to (e.g., 'accounts', 'journal')", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nxpermission',
            name='name',
            field=models.CharField(default='Permission', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nxpermission',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='users', through='accounts.CompanyMembership', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('USER', 'User'), ('VIEWER', 'Viewer')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymembershippermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymembershippermission',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='accounts.companymembership'),
        ),
        migrations.AlterField(
            model_name='companymembershippermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_grants', to='accounts.nxpermission'),
        ),
        migrations.AlterField(
            model_name='nxpermission',
            name='code',
            field=models.CharField(help_text="Permission code (e.g., 'accounts.manage', 'journal.post')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nxpermission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, help_text='The company the user is currently working in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
