# Generated by Django 4.2.25 on 2026-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_nxpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
