# Generated by Django 4.2.25 on 2026-01-25 20:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_rls_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo for reports and invoices', null=True, upload_to=accounts.models.company_logo_upload_path),
        ),
    ]
