# Generated by Django 4.2.25 on 2026-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_rls_to_fiscalperiodconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_user_id_6989e4_idx',
            old_name='accounts_em_user_id_7a1b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='accounts_em_expires_f36bd3_idx',
            old_name='accounts_em_expires_8e3c2d_idx',
        ),
    ]
