# Generated by Django 4.2.25 on 2026-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_accounts_em_user_id_7a1b5e_idx_accounts_em_user_id_6989e4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='voice_enabled',
            field=models.BooleanField(default=False, help_text='Enable voice input feature for this tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='voice_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly voice row quota (null = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='voice_quota_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the quota was last reset', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='voice_rows_used',
            field=models.PositiveIntegerField(default=0, help_text='Voice rows used this period'),
        ),
    ]
