# Generated by Django 4.2.25 on 2026-02-14 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_voice_feature_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the invitation token', max_length=64, unique=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('USER', 'User'), ('VIEWER', 'Viewer')], default='USER', max_length=20)),
                ('company_ids', models.JSONField(default=list, help_text='List of company IDs the invitee will have access to')),
                ('permission_codes', models.JSONField(default=list, help_text='List of permission codes to grant')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_user', models.ForeignKey(blank=True, help_text='The user account created from this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_origin', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('primary_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.company')),
            ],
            options={
                'verbose_name': 'User Invitation',
                'verbose_name_plural': 'User Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='accounts_in_email_0582fe_idx'), models.Index(fields=['primary_company', 'status'], name='accounts_in_primary_e6e991_idx'), models.Index(fields=['expires_at'], name='accounts_in_expires_0319bc_idx')],
            },
        ),
    ]
