# Generated by Django 4.2.25 on 2026-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_negative_inventory',
            field=models.BooleanField(default=False, help_text='Allow posting sales invoices that result in negative inventory. If False, posting will fail if insufficient stock is available.'),
        ),
    ]
