# Generated by Django 4.2.25 on 2026-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_membership_voice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enforce_subledger_tieout',
            field=models.BooleanField(default=False, help_text='Enforce AR/AP control account tie-out with subledger. If True, posting fails when AR control != sum of customer balances or AP control != sum of vendor balances.'),
        ),
        migrations.AddField(
            model_name='company',
            name='functional_currency',
            field=models.CharField(default='USD', help_text='Functional currency for accounting and reporting. All balances are stored in this currency.', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Default currency for new transactions', max_length=3),
        ),
    ]
