# Generated by Django 4.2.28 on 2026-03-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_enforce_subledger_tieout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(help_text="Module identifier matching the registry key (e.g. 'clinic', 'sales')", max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='accounts.company')),
            ],
            options={
                'ordering': ['company', 'module_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='companymodule',
            constraint=models.UniqueConstraint(fields=('company', 'module_key'), name='uniq_company_module'),
        ),
    ]
