# Generated by Django 4.2.28 on 2026-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='coa_template',
            field=models.CharField(blank=True, default='', help_text='Chart of accounts template used during onboarding (empty, minimal, retail, services).', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', help_text='Preferred date display format.', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places for amounts.'),
        ),
        migrations.AddField(
            model_name='company',
            name='decimal_separator',
            field=models.CharField(default='.', help_text='Decimal separator for number formatting.', max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the company owner has completed the setup wizard.'),
        ),
        migrations.AddField(
            model_name='company',
            name='thousand_separator',
            field=models.CharField(default=',', help_text='Thousands separator for number formatting.', max_length=5),
        ),
    ]
