# Generated by Django 4.2.28 on 2026-04-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_phone_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(blank=True, default='', help_text='Business type selected during onboarding (shopify, general).', max_length=30),
        ),
    ]
