# Generated by Django 4.2.28 on 2026-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_company_enable_arabic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pilot_profile',
            field=models.CharField(default='NONE', help_text='Constrained-pilot capability profile. Set only via activate_pilot_profile.', max_length=32),
        ),
    ]
