# Generated by Django 4.2.28 on 2026-07-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_company_pilot_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfileActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=32)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='cli', help_text="How activation was performed, e.g. 'cli'.", max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile_activations', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'activated_at'], name='accounts_pi_company_704a5c_idx')],
            },
        ),
    ]
