# Generated by Django 4.2.25 on 2026-01-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_add_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('POS', 'Point of Sale'), ('HR', 'Human Resources'), ('INVENTORY', 'Inventory Management'), ('PAYROLL', 'Payroll'), ('BANK', 'Bank Feed'), ('ERP', 'External ERP'), ('CUSTOM', 'Custom')], max_length=20)),
                ('trust_level', models.CharField(choices=[('INFORMATIONAL', 'Informational (no auto-post)'), ('OPERATIONAL', 'Operational (auto-draft)'), ('FINANCIAL', 'Financial (auto-post eligible)')], default='INFORMATIONAL', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('connection_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edim_source_systems', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('SALES', 'Sales'), ('PAYROLL', 'Payroll'), ('INVENTORY_MOVE', 'Inventory Movement'), ('JOURNAL', 'Generic Journal'), ('BANK_TRANSACTION', 'Bank Transaction'), ('CUSTOM', 'Custom')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('field_mappings', models.JSONField(default=list, help_text='List of field mapping rules: [{source_field, target_field, transform, format}]')),
                ('transform_rules', models.JSONField(default=list, help_text='Post-mapping transform rules')),
                ('defaults', models.JSONField(default=dict, help_text='Default values for unmapped fields')),
                ('validation_rules', models.JSONField(default=list, help_text='Additional validation rules')),
                ('posting_policy', models.CharField(choices=[('AUTO_DRAFT', 'Auto Draft (create as DRAFT)'), ('AUTO_POST', 'Auto Post (create and post)'), ('MANUAL_APPROVAL', 'Manual Approval (preview required)')], default='MANUAL_APPROVAL', max_length=20)),
                ('default_debit_account_code', models.CharField(blank=True, default='', max_length=20)),
                ('default_credit_account_code', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edim_mapping_profiles', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_created_profiles', to=settings.AUTH_USER_MODEL)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_profiles', to='edim.sourcesystem')),
            ],
            options={
                'ordering': ['source_system', 'document_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ingestion_type', models.CharField(choices=[('FILE_CSV', 'CSV File'), ('FILE_XLSX', 'Excel File'), ('FILE_JSON', 'JSON File'), ('API', 'API')], max_length=20)),
                ('status', models.CharField(choices=[('STAGED', 'Staged'), ('MAPPED', 'Mapped'), ('VALIDATED', 'Validated'), ('PREVIEWED', 'Previewed'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected')], default='STAGED', max_length=20)),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='edim/uploads/')),
                ('file_checksum', models.CharField(blank=True, default='', help_text='SHA-256 of uploaded file', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mapping_profile_version', models.PositiveIntegerField(blank=True, help_text='Snapshot of profile version used', null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('mapped_records', models.PositiveIntegerField(default=0)),
                ('validated_records', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('committed_entry_public_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_committed_batches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edim_batches', to='accounts.company')),
                ('mapping_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='edim.mappingprofile')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_rejected_batches', to=settings.AUTH_USER_MODEL)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='edim.sourcesystem')),
                ('staged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_staged_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('CUSTOMER', 'Customer'), ('ITEM', 'Item'), ('TAX_CODE', 'Tax Code'), ('DIMENSION', 'Analysis Dimension'), ('DIMENSION_VALUE', 'Analysis Dimension Value')], max_length=30)),
                ('external_id', models.CharField(help_text='Identifier in the external system', max_length=255)),
                ('external_label', models.CharField(blank=True, default='', help_text='Human-readable label from external system', max_length=500)),
                ('nxentra_id', models.CharField(blank=True, default='', help_text='public_id of the Nxentra entity', max_length=255)),
                ('nxentra_label', models.CharField(blank=True, default='', help_text='Human-readable label of Nxentra entity', max_length=500)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PROPOSED', 'Proposed'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edim_crosswalks', to='accounts.company')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalks', to='edim.sourcesystem')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_verified_crosswalks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_system', 'object_type', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='StagedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(help_text='Raw data from the source, exactly as parsed')),
                ('row_hash', models.CharField(help_text='SHA-256 of raw_payload', max_length=64)),
                ('mapped_payload', models.JSONField(blank=True, help_text='Canonical payload after mapping rules applied', null=True)),
                ('mapping_errors', models.JSONField(blank=True, default=list, help_text='List of mapping error messages')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error messages')),
                ('is_valid', models.BooleanField(blank=True, help_text='True if record passed validation', null=True)),
                ('resolved_accounts', models.JSONField(blank=True, default=dict, help_text='Map of external_id -> nxentra_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='edim.ingestionbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edim_staged_records', to='accounts.company')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
                'indexes': [models.Index(fields=['company', 'batch'], name='edim_staged_company_23b639_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stagedrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_edim_staged_record_row'),
        ),
        migrations.AddConstraint(
            model_name='sourcesystem',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_edim_source_system_code'),
        ),
        migrations.AddIndex(
            model_name='mappingprofile',
            index=models.Index(fields=['company', 'source_system', 'status'], name='edim_mappin_company_d0b71d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mappingprofile',
            constraint=models.UniqueConstraint(fields=('company', 'source_system', 'document_type', 'version'), name='uniq_edim_mapping_profile_version'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['company', 'status'], name='edim_ingest_company_0d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['company', 'source_system'], name='edim_ingest_company_cd827b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('file_checksum__gt', '')), fields=('company', 'file_checksum'), name='uniq_edim_batch_checksum'),
        ),
        migrations.AddIndex(
            model_name='identitycrosswalk',
            index=models.Index(fields=['company', 'source_system', 'object_type'], name='edim_identi_company_a57394_idx'),
        ),
        migrations.AddIndex(
            model_name='identitycrosswalk',
            index=models.Index(fields=['company', 'nxentra_id'], name='edim_identi_company_16f7ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='identitycrosswalk',
            constraint=models.UniqueConstraint(fields=('company', 'source_system', 'object_type', 'external_id'), name='uniq_edim_crosswalk_entry'),
        ),
    ]
