# Generated by Django 4.2.28 on 2026-02-15 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycrosswalk',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_verified_crosswalks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='committed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_committed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_rejected_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingestionbatch',
            name='staged_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_staged_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mappingprofile',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edim_created_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
