# Generated by Django 4.2.25 on 2026-02-12 20:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        ('accounts', '0016_add_voice_feature_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_number', models.CharField(help_text='Bill/Invoice number from vendor', max_length=50)),
                ('bill_date', models.DateField(help_text="Date on the vendor's bill")),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line gross amounts', max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line discounts', max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line tax amounts', max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total bill amount (subtotal - discount + tax)', max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', help_text='External reference (PO number, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Bill',
                'verbose_name_plural': 'Purchase Bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line ordering within the bill')),
                ('description', models.CharField(max_length=500)),
                ('description_ar', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line discount amount', max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tax rate at time of bill (copied from tax_code)', max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='quantity * unit_price', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='gross_amount - discount_amount', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='net_amount * tax_rate', max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='net_amount + tax_amount', max_digits=18)),
                ('account', models.ForeignKey(help_text='Expense account for this line', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasebill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('dimension_values', models.ManyToManyField(blank=True, related_name='+', to='accounting.analysisdimensionvalue')),
            ],
            options={
                'verbose_name': 'Purchase Bill Line',
                'verbose_name_plural': 'Purchase Bill Lines',
                'ordering': ['line_number'],
            },
        ),
    ]
