# Generated by Django 4.2.25 on 2026-02-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        ('accounts', '0016_add_voice_feature_fields'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillline',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Optional item reference (auto-fills defaults)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bills', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created when posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='posting_profile',
            field=models.ForeignKey(help_text='Posting profile (determines AP control account)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.postingprofile'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.vendor'),
        ),
        migrations.AddIndex(
            model_name='purchasebillline',
            index=models.Index(fields=['bill', 'line_number'], name='purchases_p_bill_id_17147d_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasebillline',
            constraint=models.UniqueConstraint(fields=('bill', 'line_number'), name='uniq_bill_line_number'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_ca0763_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'vendor'], name='purchases_p_company_7239bf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['company', 'bill_date'], name='purchases_p_company_a64c60_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(fields=('company', 'vendor', 'bill_number'), name='uniq_bill_number_per_vendor'),
        ),
    ]
