# Generated by Django 4.2.28 on 2026-03-24 05:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='currency',
            field=models.CharField(blank=True, default='', help_text='Bill currency (ISO 4217). Empty = company default currency.', max_length=3),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Exchange rate to functional currency at bill date', max_digits=18),
        ),
    ]
