# Generated by Django 4.2.28 on 2026-04-01 09:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_phone_to_user'),
        ('accounting', '0024_add_fx_rounding_account_role'),
        ('inventory', '0002_add_purchase_order_and_goods_receipt'),
        ('sales', '0006_add_credit_note_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0003_add_currency_exchange_rate_to_purchase_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_number', models.CharField(help_text='Auto-generated as GRN-XXXXXX', max_length=50)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(help_text='Auto-generated as PO-XXXXXX', max_length=50)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('FULLY_RECEIVED', 'Fully Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posting_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.postingprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='accounting.vendor')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('description_ar', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('qty_received', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('qty_billed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('dimension_values', models.ManyToManyField(blank=True, related_name='+', to='accounting.analysisdimensionvalue')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('qty_received', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Copied from PO line unit_price', max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchases.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.goodsreceipt')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Purchase order this bill is matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='po_line',
            field=models.ForeignKey(blank=True, help_text='PO line this bill line is matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='purchases.purchaseorderline'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='uniq_po_line_number'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_643d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'vendor'], name='purchases_p_company_de9604_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'order_date'], name='purchases_p_company_46cbf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='uniq_po_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'line_number'), name='uniq_gr_line_number'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['company', 'status'], name='purchases_g_company_02ad14_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['company', 'purchase_order'], name='purchases_g_company_823125_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('company', 'receipt_number'), name='uniq_grn_number_per_company'),
        ),
    ]
