# Generated by Django 4.2.28 on 2026-04-08 19:28

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_external_url_to_item'),
        ('accounting', '0024_add_fx_rounding_account_role'),
        ('accounts', '0025_add_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0004_add_purchase_order_and_goods_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credit_note_number', models.CharField(help_text='Auto-generated as PCN-XXXXXX', max_length=50)),
                ('credit_note_date', models.DateField()),
                ('reason', models.CharField(choices=[('RETURN', 'Goods Return'), ('PRICE_ADJUSTMENT', 'Price Adjustment'), ('TAX_CORRECTION', 'Tax Correction'), ('DAMAGED', 'Damaged Goods'), ('OTHER', 'Other')], default='RETURN', max_length=20)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(help_text='Original purchase bill being credited', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='purchases.purchasebill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_credit_notes', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_credit_notes', to='accounting.journalentry')),
                ('posting_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.postingprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_credit_notes', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Credit Note',
                'verbose_name_plural': 'Purchase Credit Notes',
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseCreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('description_ar', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('bill_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_lines', to='purchases.purchasebillline')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasecreditnote')),
                ('dimension_values', models.ManyToManyField(blank=True, related_name='+', to='accounting.analysisdimensionvalue')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode')),
            ],
            options={
                'verbose_name': 'Purchase Credit Note Line',
                'verbose_name_plural': 'Purchase Credit Note Lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchasecreditnoteline',
            constraint=models.UniqueConstraint(fields=('credit_note', 'line_number'), name='uniq_pcn_line_number'),
        ),
        migrations.AddIndex(
            model_name='purchasecreditnote',
            index=models.Index(fields=['company', 'status'], name='purchases_p_company_5724c2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasecreditnote',
            index=models.Index(fields=['company', 'vendor'], name='purchases_p_company_eb6457_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasecreditnote',
            index=models.Index(fields=['company', 'bill'], name='purchases_p_company_9c5d7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasecreditnote',
            constraint=models.UniqueConstraint(fields=('company', 'credit_note_number'), name='uniq_pcn_number_per_company'),
        ),
    ]
