# Generated by Django 4.2.28 on 2026-05-18 00:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_add_purchase_credit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative amount paid against this bill via vendor payments', max_digits=18),
        ),
    ]
