# Generated by Django 4.2.28 on 2026-05-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_platform_managed_locations'),
        ('purchases', '0006_add_amount_paid_to_purchase_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Receive this line into this warehouse (defaults to GR header warehouse)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse for stock receipt (direct bills only; defaults to company default)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse'),
        ),
    ]
