# Generated by Django 4.2.25 on 2026-01-14 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_nxpermission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="Event type name (e.g., 'account.created')", max_length=100)),
                ('aggregate_type', models.CharField(db_index=True, help_text="Entity type (e.g., 'Account', 'JournalEntry')", max_length=50)),
                ('aggregate_id', models.CharField(db_index=True, max_length=64)),
                ('idempotency_key', models.CharField(db_index=True, editable=False, help_text='Unique idempotency key per company', max_length=255)),
                ('sequence', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-incremented per aggregate')),
                ('company_sequence', models.BigIntegerField(db_index=True, editable=False, help_text='Monotonic event sequence per company')),
                ('data', models.JSONField(default=dict, help_text='Event data payload')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (IP, user agent, etc.)')),
                ('schema_version', models.PositiveSmallIntegerField(default=1, help_text='Schema version for data migration')),
                ('external_source', models.CharField(blank=True, default='', help_text="External system identifier (e.g., 'stripe', 'shopify')", max_length=100)),
                ('external_id', models.CharField(blank=True, default='', help_text='ID in external system', max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('caused_by_event', models.ForeignKey(blank=True, help_text='Parent event in causation chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='events.businessevent')),
                ('caused_by_user', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.company')),
            ],
            options={
                'ordering': ['company_id', 'company_sequence'],
            },
        ),
        migrations.CreateModel(
            name='EventBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(help_text="Unique consumer identifier (e.g., 'account_balance_projection')", max_length=100)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False, help_text='Pause event processing for this consumer')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Number of consecutive errors')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_bookmarks', to='accounts.company')),
                ('last_event', models.ForeignKey(blank=True, help_text='Last successfully processed event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.businessevent')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEventCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.BigIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_counter', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Event Counter',
            },
        ),
        migrations.AddConstraint(
            model_name='eventbookmark',
            constraint=models.UniqueConstraint(fields=('consumer_name', 'company'), name='uniq_bookmark_consumer_company'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['company', 'aggregate_type', 'aggregate_id', 'sequence'], name='events_busi_company_e7e21b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='events_busi_event_t_5ea4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['company', 'event_type', 'occurred_at'], name='events_busi_company_366229_idx'),
        ),
        migrations.AddIndex(
            model_name='businessevent',
            index=models.Index(fields=['caused_by_event'], name='events_busi_caused__4ce686_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.UniqueConstraint(fields=('company', 'aggregate_type', 'aggregate_id', 'sequence'), name='uniq_event_company_aggregate_sequence'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uniq_event_company_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='businessevent',
            constraint=models.UniqueConstraint(fields=('company', 'company_sequence'), name='uniq_event_company_sequence'),
        ),
    ]
