# Generated by Django 4.2.25 on 2026-02-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_add_origin_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessevent',
            name='caused_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
