# Generated by Django 4.2.28 on 2026-03-08 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_enforce_subledger_tieout_and_more'),
        ('events', '0004_alter_businessevent_caused_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'Shopify Production'.", max_length=100)),
                ('source_system', models.CharField(help_text="Identifier for the source system, e.g. 'shopify', 'clinic_erp'.", max_length=100)),
                ('key_prefix', models.CharField(editable=False, help_text='First 12 chars of the key for identification in logs.', max_length=12)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 hash of the full API key.', max_length=64, unique=True)),
                ('allowed_event_types', models.JSONField(default=list, help_text='List of event type strings this key can emit. Empty = none allowed.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_api_keys', to='accounts.company')),
            ],
            options={
                'verbose_name': 'External API Key',
                'verbose_name_plural': 'External API Keys',
                'ordering': ('-created_at',),
            },
        ),
    ]
