# Generated by Django 4.2.25 on 2026-02-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0011_alter_journalentry_created_by_and_more'),
        ('events', '0004_alter_businessevent_caused_by_user'),
        ('accounts', '0015_rename_accounts_em_user_id_7a1b5e_idx_accounts_em_user_id_6989e4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchpadRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Rows with same group_id are committed together as one JournalEntry')),
                ('group_order', models.PositiveIntegerField(default=0, help_text='Order within the group')),
                ('status', models.CharField(choices=[('RAW', 'Raw input'), ('PARSED', 'Parsed'), ('INVALID', 'Invalid'), ('READY', 'Ready'), ('COMMITTED', 'Committed')], default='RAW', max_length=12)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('paste', 'Clipboard Paste'), ('import', 'File Import'), ('voice', 'Voice Input')], default='manual', max_length=12)),
                ('transaction_date', models.DateField(blank=True, help_text='Date of the transaction (per-row, not per-entry)', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('description_ar', models.CharField(blank=True, default='', help_text='Arabic description', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes for this row')),
                ('raw_input', models.TextField(blank=True, default='', help_text='Original voice transcript, pasted text, or import row data')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error objects: [{field, code, message}]')),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, help_text='Links rows from the same import operation', null=True)),
                ('import_row_number', models.PositiveIntegerField(blank=True, help_text='Original row number from import file', null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_scratchpad_rows', to=settings.AUTH_USER_MODEL)),
                ('committed_event', models.ForeignKey(blank=True, help_text='The event created when this row was committed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scratchpad_rows', to='events.businessevent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratchpad_rows', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scratchpad_rows', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, help_text='Account to credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('debit_account', models.ForeignKey(blank=True, help_text='Account to debit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Scratchpad Row',
                'verbose_name_plural': 'Scratchpad Rows',
                'ordering': ['group_id', 'group_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScratchpadRowDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(blank=True, default='', help_text='Raw imported value before matching to a dimension value', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.analysisdimension')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.analysisdimensionvalue')),
                ('scratchpad_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='scratchpad.scratchpadrow')),
            ],
            options={
                'verbose_name': 'Scratchpad Row Dimension',
                'verbose_name_plural': 'Scratchpad Row Dimensions',
            },
        ),
        migrations.CreateModel(
            name='AccountDimensionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden'), ('OPTIONAL', 'Optional')], default='OPTIONAL', max_length=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_rules', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_rules', to='accounts.company')),
                ('default_value', models.ForeignKey(blank=True, help_text='Default value to suggest when this dimension is required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.analysisdimensionvalue')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_rules', to='accounting.analysisdimension')),
            ],
            options={
                'verbose_name': 'Account Dimension Rule',
                'verbose_name_plural': 'Account Dimension Rules',
            },
        ),
        migrations.AddConstraint(
            model_name='scratchpadrowdimension',
            constraint=models.UniqueConstraint(fields=('scratchpad_row', 'dimension'), name='uniq_scratchpad_row_dimension'),
        ),
        migrations.AddIndex(
            model_name='scratchpadrow',
            index=models.Index(fields=['company', 'status'], name='scratchpad__company_c4f7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='scratchpadrow',
            index=models.Index(fields=['company', 'group_id'], name='scratchpad__company_4e5e45_idx'),
        ),
        migrations.AddIndex(
            model_name='scratchpadrow',
            index=models.Index(fields=['company', 'created_at'], name='scratchpad__company_e3c4da_idx'),
        ),
        migrations.AddIndex(
            model_name='scratchpadrow',
            index=models.Index(fields=['company', 'source'], name='scratchpad__company_22425a_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountdimensionrule',
            constraint=models.UniqueConstraint(fields=('account', 'dimension'), name='uniq_account_dimension_rule'),
        ),
    ]
