# Generated by Django 4.2.25 on 2026-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratchpad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchpadrow',
            name='parser_output_json',
            field=models.JSONField(blank=True, help_text='Structured output from LLM parsing of voice/text input', null=True),
        ),
    ]
