# Generated by Django 4.2.25 on 2026-02-11 08:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_add_voice_feature_fields'),
        ('scratchpad', '0002_add_parser_output_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceUsageEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('audio_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Duration of audio recording in seconds', max_digits=10, null=True)),
                ('transcript_chars', models.PositiveIntegerField(default=0, help_text='Length of the transcript in characters')),
                ('asr_model', models.CharField(default='gpt-4o-transcribe', help_text='Model used for speech-to-text', max_length=50)),
                ('parse_model', models.CharField(default='gpt-4o', help_text='Model used for transaction parsing', max_length=50)),
                ('asr_input_tokens', models.PositiveIntegerField(default=0, help_text='Input tokens used by ASR (if available)')),
                ('parse_input_tokens', models.PositiveIntegerField(default=0, help_text='Input tokens used by parser')),
                ('parse_output_tokens', models.PositiveIntegerField(default=0, help_text='Output tokens generated by parser')),
                ('asr_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Estimated ASR cost in USD', max_digits=10)),
                ('parse_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Estimated parsing cost in USD', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the voice parsing succeeded')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if parsing failed')),
                ('transactions_parsed', models.PositiveIntegerField(default=0, help_text='Number of transactions parsed from the input')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_usage_events', to='accounts.company')),
                ('scratchpad_row', models.ForeignKey(blank=True, help_text='The scratchpad row created from this voice input (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_usage_events', to='scratchpad.scratchpadrow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Usage Event',
                'verbose_name_plural': 'Voice Usage Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='scratchpad__company_523760_idx'), models.Index(fields=['user', 'created_at'], name='scratchpad__user_id_de9dfb_idx'), models.Index(fields=['company', 'user', 'created_at'], name='scratchpad__company_dddb3f_idx')],
            },
        ),
    ]
