# Generated by Django 4.2.28 on 2026-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratchpad', '0003_add_voice_usage_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceusageevent',
            name='asr_model',
            field=models.CharField(default='gpt-4o-audio-preview', help_text='Model used for speech-to-text', max_length=50),
        ),
    ]
