# Generated by Django 4.2.28 on 2026-03-11 01:21
# Modified: State-only deletion since accounting now owns this table.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scratchpad', '0004_alter_voiceusageevent_asr_model'),
        ('accounting', '0022_add_dimension_kind_and_account_rules'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AccountDimensionRule',
                ),
            ],
            database_operations=[
                # No DB changes -- table is now owned by accounting app
            ],
        ),
    ]
