# Generated by Django 4.2.25 on 2026-01-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REVERSAL', 'Reversal')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='INCOMPLETE', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='chk_line_not_both_debit_credit'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__exact', 0), ('credit__exact', 0), _negated=True), name='chk_line_not_both_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='chk_line_non_negative'),
        ),
    ]
