# Generated by Django 4.2.25 on 2026-01-12 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_alter_account_options_journalentry_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('CONTRA_ASSET', 'Contra Asset'), ('CONTRA_LIABILITY', 'Contra Liability'), ('CONTRA_EQUITY', 'Contra Equity'), ('CONTRA_REVENUE', 'Contra Revenue'), ('CONTRA_EXPENSE', 'Contra Expense')], db_column='type', default='ASSET', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='is_header',
            field=models.BooleanField(default=False, help_text='Header accounts group other accounts and cannot receive postings'),
        ),
        migrations.AddField(
            model_name='account',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(blank=True, default='', help_text='Auto-generated or manual entry number', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fiscal period (1-12 or custom)', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_document',
            field=models.CharField(blank=True, default='', help_text='Reference to source document (e.g., invoice number)', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(blank=True, default='', help_text="Module that created this entry (e.g., 'inventory', 'payroll')", max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REVERSAL', 'Reversal'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Entry'), ('ADJUSTMENT', 'Adjustment')], default='NORMAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='accounting__company_528e94_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'parent'], name='accounting__company_b8cecb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='accounting__company_7eceea_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'entry_number'], name='accounting__company_40375a_idx'),
        ),
    ]
