# Generated by Django 4.2.25 on 2026-01-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_nxpermission_options_and_more'),
        ('accounting', '0004_alter_journalentry_options_remove_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAnalysisDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Account Analysis Default',
                'verbose_name_plural': 'Account Analysis Defaults',
            },
        ),
        migrations.CreateModel(
            name='AnalysisDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code: COST_CENTER, PROJECT, DEPT', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('is_required_on_posting', models.BooleanField(default=False, help_text='If True, lines must have this dimension when posting')),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_account_types', models.JSONField(blank=True, default=list, help_text='e.g., ["EXPENSE", "REVENUE"] or [] for all')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Dimension',
                'verbose_name_plural': 'Analysis Dimensions',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Dimension Value',
                'verbose_name_plural': 'Analysis Dimension Values',
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalLineAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Journal Line Analysis',
                'verbose_name_plural': 'Journal Line Analyses',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='', help_text="Unit for memo accounts: 'units', 'kg', 'hours', 'sqm', etc.", max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='memo_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalline',
            name='description_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('RECEIVABLE', 'Accounts Receivable'), ('CONTRA_ASSET', 'Contra Asset'), ('LIABILITY', 'Liability'), ('PAYABLE', 'Accounts Payable'), ('CONTRA_LIABILITY', 'Contra Liability'), ('EQUITY', 'Equity'), ('CONTRA_EQUITY', 'Contra Equity'), ('REVENUE', 'Revenue'), ('CONTRA_REVENUE', 'Contra Revenue'), ('EXPENSE', 'Expense'), ('CONTRA_EXPENSE', 'Contra Expense'), ('MEMO', 'Memo/Statistical')], db_column='type', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('NONE', 'None')], editable=False, max_length=10),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'status'], name='accounting__company_a918c9_idx'),
        ),
        migrations.AddField(
            model_name='journallineanalysis',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.analysisdimension'),
        ),
        migrations.AddField(
            model_name='journallineanalysis',
            name='dimension_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.analysisdimensionvalue'),
        ),
        migrations.AddField(
            model_name='journallineanalysis',
            name='journal_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tags', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='analysisdimensionvalue',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounting.analysisdimension'),
        ),
        migrations.AddField(
            model_name='analysisdimensionvalue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.analysisdimensionvalue'),
        ),
        migrations.AddField(
            model_name='analysisdimension',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_dimensions', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='accountanalysisdefault',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_defaults', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountanalysisdefault',
            name='default_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.analysisdimensionvalue'),
        ),
        migrations.AddField(
            model_name='accountanalysisdefault',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.analysisdimension'),
        ),
        migrations.AddIndex(
            model_name='journallineanalysis',
            index=models.Index(fields=['dimension_value'], name='accounting__dimensi_805a69_idx'),
        ),
        migrations.AddIndex(
            model_name='journallineanalysis',
            index=models.Index(fields=['dimension', 'dimension_value'], name='accounting__dimensi_f7edba_idx'),
        ),
        migrations.AddConstraint(
            model_name='journallineanalysis',
            constraint=models.UniqueConstraint(fields=('journal_line', 'dimension'), name='uniq_line_dimension'),
        ),
        migrations.AddConstraint(
            model_name='analysisdimensionvalue',
            constraint=models.UniqueConstraint(fields=('dimension', 'code'), name='uniq_dimension_value_code'),
        ),
        migrations.AddConstraint(
            model_name='analysisdimension',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_dimension_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='accountanalysisdefault',
            constraint=models.UniqueConstraint(fields=('account', 'dimension'), name='uniq_account_dimension_default'),
        ),
    ]
