# Generated by Django 4.2.25 on 2026-01-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_companysequence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companysequence',
            new_name='accounting__company_e1319e_idx',
            old_name='accounting_company_1c1d3d_idx',
        ),
    ]
