# Generated by Django 4.2.25 on 2026-02-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_statisticalentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__company_7ff753_idx',
            old_name='accounting__company_role_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__company_280069_idx',
            old_name='accounting__company_ledger_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__company_51408f_idx',
            old_name='accounting__company_cp_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='accounting__company_a2d980_idx',
            old_name='accounting__cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='accounting__company_75e779_idx',
            old_name='accounting__cust_name_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__company_776987_idx',
            old_name='accounting__line_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='accounting__company_e46efc_idx',
            old_name='accounting__line_vend_idx',
        ),
        migrations.RenameIndex(
            model_name='statisticalentry',
            new_name='accounting__company_337a82_idx',
            old_name='accounting__stat_acct_date_idx',
        ),
        migrations.RenameIndex(
            model_name='statisticalentry',
            new_name='accounting__company_88424c_idx',
            old_name='accounting__stat_status_idx',
        ),
        migrations.RenameIndex(
            model_name='statisticalentry',
            new_name='accounting__company_2c7b1c_idx',
            old_name='accounting__stat_je_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='accounting__company_ec4b20_idx',
            old_name='accounting__vend_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vendor',
            new_name='accounting__company_b860e6_idx',
            old_name='accounting__vend_name_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('RECEIVABLE', 'Accounts Receivable (Legacy)'), ('CONTRA_ASSET', 'Contra Asset (Legacy)'), ('PAYABLE', 'Accounts Payable (Legacy)'), ('CONTRA_LIABILITY', 'Contra Liability (Legacy)'), ('CONTRA_EQUITY', 'Contra Equity (Legacy)'), ('CONTRA_REVENUE', 'Contra Revenue (Legacy)'), ('CONTRA_EXPENSE', 'Contra Expense (Legacy)'), ('MEMO', 'Memo/Statistical (Legacy)')], db_column='type', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='', help_text="Unit for statistical accounts: 'units', 'kg', 'L', 'hours', 'sqm', etc.", max_length=20),
        ),
    ]
