# Generated by Django 4.2.25 on 2026-02-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_is_system_protected'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounting__company_cc9005_idx',
            old_name='accounting__company_sys_prot_idx',
        ),
    ]
