# Generated by Django 4.2.25 on 2026-02-15 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_enforce_subledger_tieout_and_more'),
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_currency', models.CharField(help_text='Source currency code (ISO 4217, e.g., USD)', max_length=3)),
                ('to_currency', models.CharField(help_text='Target currency code (ISO 4217, e.g., EUR)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate: 1 from_currency = rate to_currency', max_digits=18)),
                ('effective_date', models.DateField(help_text='Date from which this rate is effective')),
                ('rate_type', models.CharField(choices=[('SPOT', 'Spot Rate'), ('AVERAGE', 'Average Rate'), ('CLOSING', 'Closing Rate')], default='SPOT', help_text='Type of exchange rate', max_length=20)),
                ('source', models.CharField(blank=True, default='', help_text="Source of the rate (e.g., 'Manual', 'ECB', 'XE')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['company', 'from_currency', 'to_currency', 'effective_date'], name='idx_exchange_rate_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('company', 'from_currency', 'to_currency', 'effective_date', 'rate_type'), name='unique_exchange_rate_per_date'),
        ),
    ]
