# Generated by Django 4.2.28 on 2026-03-08 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_enforce_subledger_tieout_and_more'),
        ('accounting', '0019_exchangerate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text="App label of the vertical module, e.g. 'properties', 'clinic'.", max_length=50)),
                ('role', models.CharField(help_text="Account role within the module, e.g. 'RENTAL_INCOME', 'CASH_BANK'.", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_account_mappings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Module Account Mapping',
                'verbose_name_plural': 'Module Account Mappings',
                'ordering': ('module', 'role'),
                'unique_together': {('company', 'module', 'role')},
            },
        ),
    ]
