# Generated by Django 4.2.28 on 2026-03-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_add_module_account_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_number', '-date', '-id']},
        ),
    ]
