# Generated by Django 4.2.28 on 2026-03-11 01:21
# Modified: CreateModel uses SeparateDatabaseAndState since the table
# already exists as scratchpad_accountdimensionrule.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_company_module'),
        ('accounting', '0021_fix_journal_entry_ordering'),
        ('scratchpad', '0004_alter_voiceusageevent_asr_model'),
    ]

    operations = [
        # 1. Add dimension_kind field (real DB change)
        migrations.AddField(
            model_name='analysisdimension',
            name='dimension_kind',
            field=models.CharField(
                choices=[('CONTEXT', 'Context'), ('ANALYTIC', 'Analytic')],
                default='ANALYTIC',
                help_text='CONTEXT = business meaning of the transaction; ANALYTIC = optional reporting enrichment.',
                max_length=10,
            ),
        ),
        # 2. Claim AccountDimensionRule in accounting state only (table already exists)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AccountDimensionRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rule_type', models.CharField(choices=[('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden'), ('OPTIONAL', 'Optional')], default='OPTIONAL', max_length=12)),
                        ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_rules', to='accounting.account')),
                        ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_rules', to='accounts.company')),
                        ('default_value', models.ForeignKey(blank=True, help_text='Default value to suggest when this dimension is required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.analysisdimensionvalue')),
                        ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_rules', to='accounting.analysisdimension')),
                    ],
                    options={
                        'verbose_name': 'Account Dimension Rule',
                        'verbose_name_plural': 'Account Dimension Rules',
                        'db_table': 'scratchpad_accountdimensionrule',
                    },
                ),
                migrations.AddConstraint(
                    model_name='accountdimensionrule',
                    constraint=models.UniqueConstraint(fields=('account', 'dimension'), name='uniq_account_dimension_rule'),
                ),
            ],
            database_operations=[
                # No DB changes -- table already exists as scratchpad_accountdimensionrule
            ],
        ),
    ]
