# Generated by Django 4.2.28 on 2026-03-15 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_add_notification_model'),
        ('accounting', '0022_add_dimension_kind_and_account_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statement_date', models.DateField(help_text='As-of date on the bank statement')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV', 'CSV Import'), ('OFX', 'OFX/QFX Import'), ('BANK_FEED', 'Bank Feed')], default='CSV', max_length=20)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('IN_PROGRESS', 'In Progress'), ('RECONCILED', 'Reconciled')], default='IMPORTED', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The bank/cash GL account this statement is for.', on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounts.company')),
            ],
            options={
                'db_table': 'bank_statement',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciled',
            field=models.BooleanField(default=False, help_text='Whether this line has been reconciled against a bank statement'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciled_date',
            field=models.DateField(blank=True, help_text='Date this line was reconciled', null=True),
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reconciliation_date', models.DateField()),
                ('statement_closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gl_balance', models.DecimalField(decimal_places=2, help_text='GL balance for this account as of reconciliation date', max_digits=18)),
                ('adjusted_gl_balance', models.DecimalField(decimal_places=2, default=0, help_text='GL balance after outstanding items', max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Statement closing - adjusted GL = should be 0 when reconciled', max_digits=18)),
                ('matched_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
                ('outstanding_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='accounts.company')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankstatement')),
            ],
            options={
                'db_table': 'bank_reconciliation',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, help_text='Check number, transfer ref, etc.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = deposit, negative = withdrawal', max_digits=18)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('FEE', 'Fee'), ('INTEREST', 'Interest'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('AUTO_MATCHED', 'Auto-Matched'), ('MANUAL_MATCHED', 'Manual Match'), ('EXCLUDED', 'Excluded')], default='UNMATCHED', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-match confidence score (0-100)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_lines', to='accounts.company')),
                ('matched_journal_line', models.ForeignKey(blank=True, help_text='The journal line this bank transaction was matched to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='accounting.journalline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
            options={
                'db_table': 'bank_statement_line',
                'ordering': ['line_date', 'id'],
                'indexes': [models.Index(fields=['company', 'match_status'], name='bank_statem_company_41dadc_idx'), models.Index(fields=['statement', 'match_status'], name='bank_statem_stateme_31d83f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'account', 'statement_date'], name='bank_statem_company_f26001_idx'),
        ),
    ]
