# Generated by Django 4.2.28 on 2026-03-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_add_bank_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('ASSET_GENERAL', 'General Asset'), ('LIQUIDITY', 'Cash/Bank'), ('RECEIVABLE_CONTROL', 'Accounts Receivable Control'), ('INVENTORY_VALUE', 'Inventory Value'), ('PREPAID', 'Prepaid Expense'), ('FIXED_ASSET_COST', 'Fixed Asset Cost'), ('ACCUM_DEPRECIATION', 'Accumulated Depreciation'), ('OTHER_ASSET', 'Other Asset'), ('LIABILITY_GENERAL', 'General Liability'), ('PAYABLE_CONTROL', 'Accounts Payable Control'), ('ACCRUED_EXPENSE', 'Accrued Expense'), ('DEFERRED_REVENUE', 'Deferred Revenue'), ('TAX_PAYABLE', 'Tax Payable'), ('LOAN', 'Loan/Borrowing'), ('OTHER_LIABILITY', 'Other Liability'), ('CAPITAL', 'Capital'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('CURRENT_YEAR_EARNINGS', 'Current Year Earnings'), ('DRAWINGS', 'Drawings/Distributions'), ('RESERVE', 'Reserve'), ('OTHER_EQUITY', 'Other Equity'), ('SALES', 'Sales Revenue'), ('SERVICE', 'Service Revenue'), ('OTHER_INCOME', 'Other Income'), ('FINANCIAL_INCOME', 'Financial Income'), ('FX_ROUNDING', 'FX Rounding Differences'), ('CONTRA_REVENUE', 'Contra Revenue'), ('COGS', 'Cost of Goods Sold'), ('OPERATING_EXPENSE', 'Operating Expense'), ('ADMIN_EXPENSE', 'Administrative Expense'), ('FINANCIAL_EXPENSE', 'Financial Expense'), ('DEPRECIATION_EXPENSE', 'Depreciation Expense'), ('TAX_EXPENSE', 'Tax Expense'), ('OTHER_EXPENSE', 'Other Expense'), ('STAT_GENERAL', 'Statistical General'), ('STAT_INVENTORY_QTY', 'Inventory Quantity'), ('STAT_PRODUCTION_QTY', 'Production Quantity'), ('OBS_GENERAL', 'Off-Balance General'), ('OBS_CONTINGENT', 'Contingent Liability')], default='', help_text='Behavioral role that determines derived properties', max_length=30),
        ),
    ]
