# Generated by Django 4.2.28 on 2026-05-01 11:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_settlementprovider_dimension_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='difference_adjustment_entry',
            field=models.ForeignKey(blank=True, help_text='The adjustment JE that drains the EBD residual once a reason is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difference_adjustments', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='difference_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='expected_ebd_amount - bank_amount. Positive = bank short paid; negative = bank over paid. Zero for normal matches.', max_digits=18),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='difference_notes',
            field=models.CharField(blank=True, default='', help_text="Free-text note on the difference (e.g. 'Paymob support ticket #...').", max_length=255),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='difference_reason',
            field=models.CharField(blank=True, choices=[('UNRESOLVED', 'Needs review'), ('EXTRA_FEE', 'Extra gateway/courier fee'), ('BANK_CHARGE', 'Bank wire/transfer fee'), ('CHARGEBACK', 'Chargeback / dispute'), ('WRITE_OFF', 'Write-off / failed delivery'), ('ROUNDING', 'Rounding / FX'), ('OTHER', 'Other (manually noted)')], default='UNRESOLVED', help_text='Operator-selected reason for the difference. Drives the adjustment JE.', max_length=24),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='difference_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='match_status',
            field=models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('AUTO_MATCHED', 'Auto-Matched'), ('MANUAL_MATCHED', 'Manual Match'), ('MATCHED_WITH_DIFFERENCE', 'Matched (Difference)'), ('EXCLUDED', 'Excluded')], default='UNMATCHED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['company', 'difference_reason'], name='bank_statem_company_566cda_idx'),
        ),
    ]
