# Generated by Django 4.2.28 on 2026-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_a16_bankstatementline_differences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementline',
            name='match_status',
            field=models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('AUTO_MATCHED', 'Auto-Matched'), ('MANUAL_MATCHED', 'Manual Match'), ('MATCHED_WITH_DIFFERENCE', 'Matched (Difference)'), ('EXCLUDED', 'Excluded')], default='UNMATCHED', max_length=24),
        ),
    ]
