# Generated by Django 4.2.28 on 2026-05-01 14:40

import hashlib

from django.db import migrations, models


def _backfill_dedup_hashes(apps, schema_editor):
    """A17: compute dedup_hash for every existing BankStatementLine so
    that re-imports after this migration deploy can dedup against
    historical data.

    Uses the same hashing rule as accounting.bank_reconciliation
    (`_compute_line_dedup_hash`); kept inline here to avoid coupling the
    migration to the application module's import-time state.
    """
    BankStatementLine = apps.get_model("accounting", "BankStatementLine")
    batch = []
    BATCH_SIZE = 500
    for line in BankStatementLine.objects.only(
        "id", "line_date", "amount", "reference", "description"
    ).iterator():
        payload = (
            f"{line.line_date.isoformat() if line.line_date else ''}|"
            f"{line.amount}|"
            f"{(line.reference or '').strip()}|"
            f"{(line.description or '').strip()}"
        )
        line.dedup_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()
        batch.append(line)
        if len(batch) >= BATCH_SIZE:
            BankStatementLine.objects.bulk_update(batch, ["dedup_hash"])
            batch = []
    if batch:
        BankStatementLine.objects.bulk_update(batch, ["dedup_hash"])


def _noop_reverse(apps, schema_editor):
    """Reverse: clearing the column happens via RemoveField; no per-row work."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_a16_bankstatementline_match_status_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='dedup_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hex digest of (line_date|amount|reference|description). Empty for legacy rows from before A17.', max_length=64),
        ),
        migrations.RunPython(_backfill_dedup_hashes, reverse_code=_noop_reverse),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['company', 'dedup_hash'], name='bank_statem_company_e94ed1_idx'),
        ),
    ]
