# Generated by Django 4.2.28 on 2026-05-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_a85_period_override_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoverrideaudit',
            name='source_document_ref',
            field=models.CharField(blank=True, default='', help_text="Free-text identifier of the override target — e.g. 'PAYMOB-BATCH-X' for a settlement import, 'JE-000042' for a manual JE.", max_length=255),
        ),
    ]
