# Generated by Django 4.2.28 on 2026-05-26 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_periodoverrideaudit_source_document_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='event_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='A86 shadow: confirmed_at from the latest MatchConfirmed event.', null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='event_last_match_event_id',
            field=models.UUIDField(blank=True, help_text='A86 shadow: BusinessEvent.id of the latest Match{Confirmed,Unmatched} event applied. Lets the projection skip already-applied events during rebuild (defense beyond ProjectionAppliedEvent).', null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='event_match_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A86 shadow: confidence from the latest MatchConfirmed event.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='event_match_status',
            field=models.CharField(blank=True, choices=[('UNMATCHED', 'Unmatched'), ('AUTO_MATCHED', 'Auto-Matched'), ('MANUAL_MATCHED', 'Manual Match'), ('MATCHED_WITH_DIFFERENCE', 'Matched (Difference)'), ('EXCLUDED', 'Excluded')], default='', help_text="A86 shadow: derived from ReconciliationMatch* events. Empty (not UNMATCHED) when no Confirmed/Unmatched event has been applied yet — distinguishes 'never matched' from 'matched then unmatched'.", max_length=24),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='event_matched_journal_line',
            field=models.ForeignKey(blank=True, help_text='A86 shadow: from ReconciliationMatchConfirmed events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_bank_matches', to='accounting.journalline'),
        ),
    ]
