# Generated by Django 4.2.28 on 2026-08-22 16:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_pilotprofileactivation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0039_unify_stripe_module_account_mapping_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRejectedRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("SETTLEMENT", "Settlement import"), ("BANK", "Bank statement import")], max_length=20
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(blank=True, help_text="paymob/bosta; blank for bank", max_length=50),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "import_batch_id",
                    models.UUIDField(db_index=True, help_text="One id per upload; groups a file's rejects"),
                ),
                ("row_index", models.PositiveIntegerField(help_text="1-based position of the row in the source file")),
                (
                    "raw_row",
                    models.JSONField(default=dict, help_text="Full original row as parsed (K#3: keep the evidence)"),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("EMPTY_BATCH_ID", "Empty settlement batch id"),
                            ("MALFORMED_NUMERIC", "Malformed numeric cell"),
                            ("UNPARSEABLE_AMOUNT", "Unparseable amount"),
                            ("UNPARSEABLE_DATE", "Unparseable date"),
                            ("ZERO_AMOUNT", "Zero amount"),
                            ("DUPLICATE", "Duplicate row"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("REJECTED", "Rejected"), ("QUARANTINED", "Quarantined")],
                        default="REJECTED",
                        max_length=20,
                    ),
                ),
                (
                    "dedup_hash",
                    models.CharField(
                        help_text="Stable per (company, import identity, row) so a re-import bumps occurrence_count",
                        max_length=64,
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_rejected_rows",
                        to="accounts.company",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank commit-time rejects link their statement; null for settlement / parse-time / deleted statement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_rows",
                        to="accounting.bankstatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import-rejected row",
                "verbose_name_plural": "Import-rejected rows",
                "db_table": "import_rejected_row",
                "indexes": [
                    models.Index(fields=["company", "resolved", "-last_seen_at"], name="idx_irr_company_unresolved"),
                    models.Index(
                        fields=["company", "source_kind", "import_batch_id"], name="idx_irr_company_kind_batch"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="importrejectedrow",
            constraint=models.UniqueConstraint(fields=("company", "dedup_hash"), name="uniq_import_rejected_row"),
        ),
    ]
