# Generated by Django 4.2.28 on 2026-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_import_rejected_row_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrejectedrow',
            name='reason_code',
            field=models.CharField(choices=[('EMPTY_BATCH_ID', 'Empty settlement batch id'), ('MALFORMED_NUMERIC', 'Malformed numeric cell'), ('UNPARSEABLE_AMOUNT', 'Unparseable amount'), ('UNPARSEABLE_DATE', 'Unparseable date'), ('ZERO_AMOUNT', 'Zero amount'), ('DUPLICATE', 'Duplicate row'), ('ORPHAN_ORDER_ID', 'Orphan order id (posted, needs review)')], max_length=30),
        ),
    ]
