# Generated by Django 4.2.28 on 2026-04-19 20:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0024_add_fx_rounding_account_role'),
        ('accounts', '0026_add_tos_consent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(help_text='Platform connector (shopify, stripe, amazon, etc.)', max_length=50)),
                ('platform_document_id', models.CharField(help_text='External ID (payout ID, dispute ID, etc.)', max_length=100)),
                ('settlement_type', models.CharField(choices=[('PAYOUT', 'Payout'), ('FEE', 'Fee'), ('DISPUTE', 'Dispute / Chargeback'), ('DISPUTE_WON', 'Dispute Won / Reversed'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gross amount before fees', max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform fees deducted', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount (gross - fees). For payouts: amount deposited to bank.', max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('settlement_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('auto_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_settlements', to='accounts.company')),
                ('matched_bank_line', models.ForeignKey(blank=True, help_text='Matched bank statement line (for reconciliation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settlements', to='accounting.bankstatementline')),
                ('posted_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created when posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settlements', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Platform Settlement',
                'verbose_name_plural': 'Platform Settlements',
                'db_table': 'platform_settlement',
                'ordering': ['-settlement_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'platform', 'settlement_type'], name='platform_se_company_19d29c_idx'), models.Index(fields=['company', 'settlement_date'], name='platform_se_company_217312_idx'), models.Index(fields=['company', 'status'], name='platform_se_company_775913_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='platformsettlement',
            constraint=models.UniqueConstraint(fields=('company', 'platform', 'platform_document_id', 'settlement_type'), name='uniq_platform_settlement'),
        ),
    ]
