# Generated by Django 4.2.25 on 2026-06-22 21:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_add_tos_consent_fields"),
        ("platform_connectors", "0001_add_platform_settlement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderRawObject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=40)),
                ("object_type", models.CharField(max_length=60)),
                ("external_id", models.CharField(max_length=255)),
                ("api_version", models.CharField(blank=True, default="", max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API pull"),
                            ("webhook", "Webhook"),
                            ("report", "Reporting API / report"),
                            ("csv", "CSV import"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(help_text="When WE fetched/received it (not the provider's created time)."),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_raw_objects",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Raw Object",
                "verbose_name_plural": "Provider Raw Objects",
                "db_table": "provider_raw_object",
                "ordering": ["-fetched_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["company", "provider", "object_type"], name="provider_ra_company_659b74_idx"),
                    models.Index(fields=["company", "provider", "external_id"], name="provider_ra_company_6c6d5c_idx"),
                    models.Index(fields=["company", "payload_hash"], name="provider_ra_company_93864c_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="providerrawobject",
            constraint=models.UniqueConstraint(
                fields=("company", "provider", "object_type", "external_id", "payload_hash"),
                name="uniq_provider_raw_object",
            ),
        ),
    ]
