# Generated by Django 4.2.25 on 2026-06-27 09:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_tos_consent_fields'),
        ('platform_connectors', '0003_provider_raw_object_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayoutLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('payout_batch_id', models.CharField(max_length=255)),
                ('line_index', models.PositiveIntegerField()),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_payout_lines', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Provider Payout Line',
                'verbose_name_plural': 'Provider Payout Lines',
                'db_table': 'provider_payout_line',
                'ordering': ['company', 'provider', 'payout_batch_id', 'line_index'],
                'indexes': [models.Index(fields=['company', 'provider', 'payout_batch_id'], name='provider_pa_company_f3535b_idx'), models.Index(fields=['company', 'provider', 'source_id'], name='provider_pa_company_cca59f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerpayoutline',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'payout_batch_id', 'line_index'), name='uniq_provider_payout_line'),
        ),
    ]
