# Generated by Django 4.2.25 on 2026-06-27 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connectors', '0005_provider_payout_line_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoutline',
            name='uncollected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
