# Generated by Django 4.2.25 on 2026-06-27 12:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_tos_consent_fields'),
        ('platform_connectors', '0006_providerpayoutline_uncollected_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('payout_batch_id', models.CharField(max_length=255)),
                ('provider_status', models.CharField(blank=True, max_length=40)),
                ('provider_account_reference', models.CharField(blank=True, max_length=255)),
                ('provider_account_name', models.CharField(blank=True, max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('uncollected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_payouts', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Provider Payout',
                'verbose_name_plural': 'Provider Payouts',
                'db_table': 'provider_payout',
                'ordering': ['company', 'provider', '-payout_date'],
                'indexes': [models.Index(fields=['company', 'provider'], name='provider_pa_company_10453a_idx'), models.Index(fields=['company', 'provider', 'provider_status'], name='provider_pa_company_70ddf6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='providerpayout',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'payout_batch_id'), name='uniq_provider_payout'),
        ),
    ]
