# Generated by Django 4.2.28 on 2026-07-05 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connectors', '0008_provider_payout_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayout',
            name='fee_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='gross_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='matched_line_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='net_variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='reconciliation_outcome',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='reconciliation_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='unmatched_line_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerpayout',
            name='verified_line_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='match_kind',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='matched_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='matched_ref_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='provider_line_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerpayoutline',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='providerpayoutline',
            index=models.Index(fields=['company', 'provider', 'payout_batch_id', 'verified'], name='provider_pa_company_be63b6_idx'),
        ),
    ]
