# Generated by Django 4.2.28 on 2026-03-16 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_add_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_account_id', models.CharField(help_text='Stripe account ID (acct_...)', max_length=255)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('livemode', models.BooleanField(default=False)),
                ('webhook_secret', models.CharField(default='', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_accounts', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'stripe_account_id')},
            },
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_charge_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(default='', max_length=500)),
                ('customer_email', models.CharField(default='', max_length=255)),
                ('customer_name', models.CharField(default='', max_length=255)),
                ('charge_date', models.DateField()),
                ('stripe_created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='stripe_connector.stripeaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_charges', to='accounts.company')),
            ],
            options={
                'ordering': ['-stripe_created_at'],
                'unique_together': {('company', 'stripe_charge_id')},
            },
        ),
        migrations.CreateModel(
            name='StripePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_payout_id', models.CharField(db_index=True, max_length=255)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('stripe_status', models.CharField(default='', max_length=30)),
                ('payout_date', models.DateField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='stripe_connector.stripeaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payouts', to='accounts.company')),
            ],
            options={
                'ordering': ['-payout_date'],
                'unique_together': {('company', 'stripe_payout_id')},
            },
        ),
        migrations.CreateModel(
            name='StripeRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_refund_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(default='', max_length=255)),
                ('stripe_created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='stripe_connector.stripecharge')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_refunds', to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'stripe_refund_id')},
            },
        ),
        migrations.CreateModel(
            name='StripePayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_balance_txn_id', models.CharField(db_index=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('payout', 'Payout'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('source_id', models.CharField(default='', help_text='Source charge/refund ID', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payout_transactions', to='accounts.company')),
                ('local_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_transactions', to='stripe_connector.stripecharge')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stripe_connector.stripepayout')),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('company', 'stripe_balance_txn_id')},
            },
        ),
    ]
