# Generated by Django 4.2.25 on 2026-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeaccount',
            name='auth_type',
            field=models.CharField(choices=[('restricted_key', 'Restricted read-only API key'), ('oauth', 'OAuth (Stripe App)')], default='restricted_key', max_length=20),
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='credential_ref',
            field=models.TextField(blank=True, default='', help_text="Read credential for pulling this account's data — a restricted read-only API key (Phase 1) or an OAuth token reference (Stripe App). Plaintext today; MUST be encrypted at rest (A47) before a real credential is stored — that gates Phase 1. See ADR-0002."),
        ),
    ]
