# Generated by Django 4.2.25 on 2026-06-23 07:26
#
# A47: widen credential columns to TEXT + swap to EncryptedTextField, then
# encrypt any pre-existing plaintext rows in place. Raw SQL + is_encrypted()
# guard = idempotent (see the matching shopify_connector.0017 for the rationale).
# In practice production rows are empty today (no connect UI writes these yet),
# so this is a no-op there — but it correctly handles seeded/demo rows and keeps
# the rollout symmetric with Shopify.

from django.db import migrations

import nxentra_backend.crypto

_TARGETS = [
    ("stripe_connector", "StripeAccount", ["webhook_secret", "credential_ref"]),
]


def _rewrite(apps, schema_editor, transform):
    from accounts.rls import rls_bypass

    conn = schema_editor.connection
    with rls_bypass(conn=conn):
        with conn.cursor() as cur:
            for app_label, model_name, field_names in _TARGETS:
                model = apps.get_model(app_label, model_name)
                table = model._meta.db_table
                pk_col = model._meta.pk.column
                for fname in field_names:
                    col = model._meta.get_field(fname).column
                    cur.execute(f'SELECT "{pk_col}", "{col}" FROM "{table}"')
                    for pk, value in cur.fetchall():
                        new_value = transform(value)
                        if new_value is not None and new_value != value:
                            cur.execute(
                                f'UPDATE "{table}" SET "{col}" = %s WHERE "{pk_col}" = %s',
                                [new_value, pk],
                            )


def encrypt_existing(apps, schema_editor):
    from nxentra_backend.crypto import encrypt_secret, is_encrypted

    def transform(value):
        if value and not is_encrypted(value):
            return encrypt_secret(value)
        return None

    _rewrite(apps, schema_editor, transform)


def decrypt_existing(apps, schema_editor):
    from nxentra_backend.crypto import decrypt_secret, is_encrypted

    def transform(value):
        if is_encrypted(value):
            return decrypt_secret(value)
        return None

    _rewrite(apps, schema_editor, transform)


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_connector', '0002_stripeaccount_auth_type_stripeaccount_credential_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='credential_ref',
            field=nxentra_backend.crypto.EncryptedTextField(blank=True, default='', help_text="Read credential for pulling this account's data — a restricted read-only API key (Phase 1) or an OAuth token reference (Stripe App). Encrypted at rest (A47). See ADR-0002."),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='webhook_secret',
            field=nxentra_backend.crypto.EncryptedTextField(blank=True, default='', help_text='Stripe webhook signing secret (whsec_*). Encrypted at rest (A47).'),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
