import Link from "next/link";
import Head from "next/head";

export default function TermsOfServicePage() {
  return (
    <>
      <Head>
        <title>Terms of Service - Nxentra</title>
      </Head>
      <div className="fixed inset-0 overflow-y-auto bg-background text-foreground">
        <div className="mx-auto max-w-3xl px-6 py-16">
          <nav className="mb-12">
            <Link href="/" className="text-sm text-accent hover:underline">
              &larr; Back to Nxentra
            </Link>
          </nav>

          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mb-8">
            Version 1.0 &mdash; Effective Date: April 12, 2026
          </p>

          <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">1. Agreement to Terms</h2>
              <p>
                By accessing or using the Nxentra platform (&quot;Service&quot;), you agree to be bound by these
                Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not access
                or use the Service. These Terms constitute a legally binding agreement between you
                (&quot;User&quot;, &quot;you&quot;) and Nxentra (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">2. Description of Service</h2>
              <p>
                Nxentra is a cloud-based accounting and enterprise resource planning (ERP) platform
                that provides financial management, invoicing, inventory tracking, bank reconciliation,
                and third-party integrations (including Shopify and Stripe). The Service is provided
                on a software-as-a-service (SaaS) basis.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">3. Account Registration</h2>
              <p>
                To use the Service, you must create an account by providing accurate and complete
                information. You are responsible for maintaining the confidentiality of your account
                credentials and for all activities that occur under your account. You must notify us
                immediately of any unauthorized use of your account.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">4. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations</li>
                <li>Attempt to gain unauthorized access to any part of the Service or its related systems</li>
                <li>Transmit any malicious code, viruses, or harmful data through the Service</li>
                <li>Use the Service to store or process data that you do not have the right to use</li>
                <li>Interfere with or disrupt the integrity or performance of the Service</li>
                <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
                <li>Resell, sublicense, or redistribute access to the Service without written consent</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">5. Data Ownership</h2>
              <p>
                You retain all ownership rights to the data you enter into the Service (&quot;Your Data&quot;).
                We do not claim ownership of Your Data. You grant us a limited license to host,
                store, process, and display Your Data solely for the purpose of providing the Service
                to you. Upon termination of your account, you may request an export of Your Data
                within 30 days.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">6. Financial Data Disclaimer</h2>
              <p>
                The Service provides tools for financial record-keeping and reporting. It is NOT a
                substitute for professional accounting, tax, or legal advice. You are solely
                responsible for the accuracy, completeness, and legality of the financial data you
                enter and the decisions you make based on reports generated by the Service. Nxentra
                is not liable for any errors in your financial records, tax filings, or business
                decisions made using the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">7. Service Availability</h2>
              <p>
                We strive to maintain high availability of the Service but do not guarantee
                uninterrupted access. The Service may be temporarily unavailable due to maintenance,
                updates, or circumstances beyond our control. We will make reasonable efforts to
                provide advance notice of scheduled maintenance. The Service is currently in a
                testing/pilot phase and may contain bugs or incomplete features.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">8. Third-Party Integrations</h2>
              <p>
                The Service may integrate with third-party platforms (e.g., Shopify, Stripe). Your
                use of these integrations is subject to the respective third-party terms and privacy
                policies. We are not responsible for the availability, accuracy, or security of
                third-party services. You authorize us to access your third-party accounts solely
                to provide the integration features you enable.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">9. Intellectual Property</h2>
              <p>
                The Service, including its source code, design, documentation, trademarks, and all
                related intellectual property, is owned by Nxentra and protected by copyright and
                other intellectual property laws. These Terms do not grant you any rights to our
                intellectual property except the limited right to use the Service as described herein.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">10. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NXENTRA SHALL NOT BE LIABLE FOR
                ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS
                OF PROFITS, REVENUE, DATA, OR BUSINESS OPPORTUNITIES ARISING OUT OF OR RELATED TO
                YOUR USE OF THE SERVICE. OUR TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE AMOUNTS
                PAID BY YOU TO NXENTRA IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">11. Indemnification</h2>
              <p>
                You agree to indemnify and hold harmless Nxentra, its officers, directors, employees,
                and agents from any claims, damages, losses, liabilities, and expenses (including
                reasonable legal fees) arising out of or related to your use of the Service, your
                violation of these Terms, or your violation of any rights of a third party.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">12. Termination</h2>
              <p>
                Either party may terminate this agreement at any time. We may suspend or terminate
                your access to the Service immediately if you violate these Terms. Upon termination,
                your right to use the Service ceases immediately. Sections 5, 6, 10, 11, and 13
                survive termination.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">13. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the
                jurisdiction in which Nxentra operates, without regard to conflict of law principles.
                Any disputes arising under these Terms shall be resolved through good-faith
                negotiation, and if unresolved, through binding arbitration.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">14. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. When we make material changes, we will
                notify you via email or through the Service. Your continued use of the Service after
                such changes constitutes acceptance of the updated Terms. If you do not agree to the
                updated Terms, you must stop using the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-8 mb-3">15. Contact</h2>
              <p>
                If you have any questions about these Terms, please contact us at:{" "}
                <a href="mailto:admin@nxentra.com" className="text-accent underline">
                  admin@nxentra.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
