# Generated by Django 4.2.28 on 2026-02-15 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_seed_tenant_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdirectory',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for API exposure.', unique=True),
        ),
    ]
