# Generated by Django 4.2.25 on 2026-02-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_company_allow_negative_inventory'),
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerSequenceCounter',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_ledger_counter', serialize=False, to='accounts.company')),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stock Ledger Sequence Counter',
                'verbose_name_plural': 'Stock Ledger Sequence Counters',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Warehouse code (e.g., MAIN, WH-01)', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='', help_text='Physical address of the warehouse')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default warehouse for new transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField(editable=False, help_text='Sequential order within company (monotonic)')),
                ('source_type', models.CharField(choices=[('PURCHASE_BILL', 'Purchase Bill'), ('SALES_INVOICE', 'Sales Invoice'), ('ADJUSTMENT', 'Inventory Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('TRANSFER_IN', 'Warehouse Transfer In'), ('TRANSFER_OUT', 'Warehouse Transfer Out'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return')], help_text='Type of document that created this entry', max_length=20)),
                ('source_id', models.UUIDField(help_text='Public ID of source document (bill, invoice, adjustment)')),
                ('source_line_id', models.UUIDField(blank=True, help_text='Public ID of source document line (for line-level tracking)', null=True)),
                ('qty_delta', models.DecimalField(decimal_places=4, help_text='Quantity change: positive = IN, negative = OUT', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, help_text='Unit cost in base currency. For IN: purchase cost. For OUT: issue cost (avg_cost at time of issue).', max_digits=18)),
                ('value_delta', models.DecimalField(decimal_places=2, help_text='Value change = qty_delta * unit_cost', max_digits=18)),
                ('costing_method_snapshot', models.CharField(help_text='Costing method used at time of entry (WEIGHTED_AVERAGE, FIFO, LIFO)', max_length=20)),
                ('qty_balance_after', models.DecimalField(decimal_places=4, help_text='Quantity on hand after this entry', max_digits=18)),
                ('value_balance_after', models.DecimalField(decimal_places=2, help_text='Total stock value after this entry', max_digits=18)),
                ('avg_cost_after', models.DecimalField(decimal_places=6, help_text='Weighted average cost after this entry', max_digits=18)),
                ('posted_at', models.DateTimeField(help_text='Timestamp when this entry was posted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='accounts.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='sales.item')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Corresponding accounting journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_entries', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, help_text='User who posted this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_active'], name='inventory_w_company_ab385b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'is_default'], name='inventory_w_company_2c06fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_warehouse_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'item', 'warehouse'], name='inventory_s_company_b5a9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'sequence'], name='inventory_s_company_4c3f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='inventory_s_company_238c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'posted_at'], name='inventory_s_company_0efb80_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'item', 'posted_at'], name='inventory_s_company_9374ef_idx'),
        ),
    ]
