# Generated by Django 4.2.28 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledgerentry',
            name='source_type',
            field=models.CharField(choices=[('PURCHASE_BILL', 'Purchase Bill'), ('SALES_INVOICE', 'Sales Invoice'), ('ADJUSTMENT', 'Inventory Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('TRANSFER_IN', 'Warehouse Transfer In'), ('TRANSFER_OUT', 'Warehouse Transfer Out'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('GOODS_RECEIPT', 'Goods Receipt')], help_text='Type of document that created this entry', max_length=20),
        ),
    ]
