# Generated by Django 4.2.28 on 2026-04-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_credit_note_models'),
        ('accounts', '0024_add_phone_to_user'),
        ('inventory', '0002_add_purchase_order_and_goods_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifoLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_original', models.DecimalField(decimal_places=4, help_text='Original quantity received in this layer', max_digits=18)),
                ('qty_remaining', models.DecimalField(decimal_places=4, help_text='Quantity remaining in this layer (decremented by FIFO issues)', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, help_text='Unit cost at time of receipt (immutable)', max_digits=18)),
                ('sequence', models.PositiveIntegerField(help_text='Receipt sequence for FIFO ordering (lower = older = consumed first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_layers', to='accounts.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layers', to='sales.item')),
                ('receipt_entry', models.ForeignKey(help_text='The stock ledger entry that created this FIFO layer', on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layer', to='inventory.stockledgerentry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fifo_layers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'FIFO Layer',
                'verbose_name_plural': 'FIFO Layers',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['company', 'item', 'warehouse', 'sequence'], name='inventory_f_company_005c25_idx'), models.Index(fields=['company', 'item', 'warehouse', 'qty_remaining'], name='inventory_f_company_d53b29_idx')],
            },
        ),
    ]
