# Generated by Django 4.2.28 on 2026-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_fifo_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_platform_managed',
            field=models.BooleanField(default=False, help_text='If True, stock is synced from the platform. Manual edits are blocked.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time stock levels were synced from the platform.', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='platform',
            field=models.CharField(blank=True, default='', help_text='Platform connector that manages this location (e.g., shopify, amazon). Empty = manual.', max_length=50),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='platform_location_id',
            field=models.CharField(blank=True, default='', help_text='External location ID from the platform (e.g., Shopify location_id).', max_length=100),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'platform', 'is_platform_managed'], name='inventory_w_company_90c724_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform_managed', True)), fields=('company', 'platform', 'platform_location_id'), name='uniq_platform_location_per_company'),
        ),
    ]
