# Generated by Django 4.2.28 on 2026-05-20 00:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_tos_consent_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_add_line_warehouse'),
        ('inventory', '0004_add_platform_managed_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transfer_number', models.CharField(help_text='Auto-generated as TRF-XXXXXX', max_length=50)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField()),
                ('qty', models.DecimalField(decimal_places=4, help_text='Quantity to transfer from source to destination', max_digits=18)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Source avg_cost at posting time (filled by post_inventory_transfer)', max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorytransfer')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorytransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'line_number'), name='uniq_transfer_line_number'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['company', 'status'], name='inventory_i_company_7f2bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransfer',
            index=models.Index(fields=['company', 'transfer_date'], name='inventory_i_company_835b24_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransfer',
            constraint=models.UniqueConstraint(fields=('company', 'transfer_number'), name='uniq_transfer_number_per_company'),
        ),
    ]
