# Generated by Django 4.2.25 on 2026-02-12 20:06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        ('accounts', '0016_add_voice_feature_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Item code (e.g., ITEM001)', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_ar', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('EXPENSE', 'Expense')], default='PRODUCT', max_length=20)),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default selling price', max_digits=18)),
                ('default_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default purchase cost', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PostingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Profile code (e.g., AR-DEFAULT, AP-FOREIGN)', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('profile_type', models.CharField(choices=[('CUSTOMER', 'Customer (AR)'), ('VENDOR', 'Vendor (AP)')], help_text='CUSTOMER for AR, VENDOR for AP', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default profile for this type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_profiles', to='accounts.company')),
                ('control_account', models.ForeignKey(help_text='Control account (AR or AP)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Posting Profile',
                'verbose_name_plural': 'Posting Profiles',
                'ordering': ['profile_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(help_text='Invoice number (can be auto-generated)', max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line gross amounts', max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line discounts', max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of line tax amounts', max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total invoice amount (subtotal - discount + tax)', max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', help_text='External reference (PO number, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created when posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.journalentry')),
                ('posting_profile', models.ForeignKey(help_text='Posting profile (determines AR control account)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.postingprofile')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Tax code (e.g., VAT15, ZERO)', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g., 0.15 = 15%)', max_digits=5)),
                ('direction', models.CharField(choices=[('INPUT', 'Input (Purchases)'), ('OUTPUT', 'Output (Sales)')], help_text='INPUT for purchases (deductible), OUTPUT for sales (collected)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='accounts.company')),
                ('tax_account', models.ForeignKey(help_text='GL account for tax (VAT Payable for OUTPUT, Input VAT for INPUT)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Tax Code',
                'verbose_name_plural': 'Tax Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField(help_text='Line ordering within the invoice')),
                ('description', models.CharField(max_length=500)),
                ('description_ar', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line discount amount', max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tax rate at time of invoice (copied from tax_code)', max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='quantity * unit_price', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='gross_amount - discount_amount', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='net_amount * tax_rate', max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='net_amount + tax_amount', max_digits=18)),
                ('account', models.ForeignKey(help_text='Revenue account for this line', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('dimension_values', models.ManyToManyField(blank=True, related_name='+', to='accounting.analysisdimensionvalue')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(blank=True, help_text='Optional item reference (auto-fills defaults)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode')),
            ],
            options={
                'verbose_name': 'Sales Invoice Line',
                'verbose_name_plural': 'Sales Invoice Lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default tax code for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='Default expense account for purchases', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, help_text='Default revenue account for sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddIndex(
            model_name='taxcode',
            index=models.Index(fields=['company', 'direction', 'is_active'], name='sales_taxco_company_5bcef0_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_taxcode_per_company'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['invoice', 'line_number'], name='sales_sales_invoice_d8b11f_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='uniq_invoice_line_number'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_6012fa_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_593a97_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'invoice_date'], name='sales_sales_company_0a60a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_invoice_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='postingprofile',
            index=models.Index(fields=['company', 'profile_type', 'is_active'], name='sales_posti_company_71ff97_idx'),
        ),
        migrations.AddConstraint(
            model_name='postingprofile',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_postingprofile_per_company'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'is_active'], name='sales_item_company_9f7473_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_item_code_per_company'),
        ),
    ]
