# Generated by Django 4.2.25 on 2026-02-14 10:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, help_text='Current weighted average cost (auto-calculated)', max_digits=18),
        ),
        migrations.AddField(
            model_name='item',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cost of Goods Sold account (required for INVENTORY items)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='costing_method',
            field=models.CharField(choices=[('WEIGHTED_AVERAGE', 'Weighted Average'), ('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out')], default='WEIGHTED_AVERAGE', help_text='Costing method for inventory valuation', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Inventory asset account (required for INVENTORY items)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), editable=False, help_text='Last purchase cost (auto-calculated)', max_digits=18),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(blank=True, default='', help_text='Unit of measure (e.g., EA, KG, BOX)', max_length=20),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='recoverable',
            field=models.BooleanField(default=True, help_text='For INPUT (purchase) taxes: If True, tax is recoverable and goes to Input VAT account. If False, tax is non-recoverable and capitalizes into the inventory/expense cost. Has no effect on OUTPUT taxes.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('INVENTORY', 'Inventory Item'), ('SERVICE', 'Service'), ('NON_STOCK', 'Non-Stock Item')], default='INVENTORY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'item_type', 'is_active'], name='sales_item_company_864a09_idx'),
        ),
    ]
