# Generated by Django 4.2.25 on 2026-02-16 07:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_enforce_subledger_tieout_and_more'),
        ('accounting', '0019_exchangerate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_migrate_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount paid against this invoice', max_digits=18),
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_public_id', models.UUIDField(help_text='Public ID of the customer receipt')),
                ('receipt_date', models.DateField(help_text='Date of the receipt')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this invoice', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_allocations', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Receipt Allocation',
                'verbose_name_plural': 'Receipt Allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'receipt_public_id'], name='sales_recei_company_a4bc9d_idx'), models.Index(fields=['company', 'invoice'], name='sales_recei_company_6e4e46_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_public_id', models.UUIDField(help_text='Public ID of the vendor payment')),
                ('payment_date', models.DateField(help_text='Date of the payment')),
                ('bill_reference', models.CharField(help_text='Vendor bill/invoice reference number', max_length=100)),
                ('bill_date', models.DateField(blank=True, help_text='Original bill date', null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original bill total amount', max_digits=18, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this bill', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'payment_public_id'], name='sales_payme_company_c7cd4e_idx'), models.Index(fields=['company', 'vendor'], name='sales_payme_company_3bc31f_idx'), models.Index(fields=['company', 'bill_reference'], name='sales_payme_company_ca62be_idx')],
            },
        ),
    ]
