# Generated by Django 4.2.28 on 2026-03-24 01:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_amount_paid_receiptallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.CharField(blank=True, default='', help_text='Invoice currency (ISO 4217). Empty = company default currency.', max_length=3),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Exchange rate to functional currency at invoice date', max_digits=18),
        ),
    ]
