# Generated by Django 4.2.28 on 2026-03-31 21:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0024_add_fx_rounding_account_role'),
        ('accounts', '0024_add_phone_to_user'),
        ('sales', '0005_add_currency_to_sales_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credit_note_number', models.CharField(help_text='Credit note number (auto-generated as CN-XXXXXX)', max_length=50)),
                ('credit_note_date', models.DateField()),
                ('reason', models.CharField(choices=[('RETURN', 'Goods returned'), ('PRICE_ADJUSTMENT', 'Price adjustment'), ('TAX_CORRECTION', 'Tax correction'), ('DAMAGED', 'Damaged goods'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reason_notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOIDED', 'Voided')], default='DRAFT', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_credit_notes', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounting.customer')),
                ('invoice', models.ForeignKey(help_text='The original invoice being credited', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_credit_notes', to='accounting.journalentry')),
                ('posting_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.postingprofile')),
            ],
            options={
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesCreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('description_ar', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salescreditnote')),
                ('dimension_values', models.ManyToManyField(blank=True, related_name='+', to='accounting.analysisdimensionvalue')),
                ('invoice_line', models.ForeignKey(blank=True, help_text='Original invoice line being credited (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_lines', to='sales.salesinvoiceline')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.item')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.taxcode')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='salescreditnoteline',
            constraint=models.UniqueConstraint(fields=('credit_note', 'line_number'), name='uniq_credit_note_line_number'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_332321_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_36d6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'invoice'], name='sales_sales_company_71b2f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescreditnote',
            constraint=models.UniqueConstraint(fields=('company', 'credit_note_number'), name='uniq_credit_note_number_per_company'),
        ),
    ]
