# Generated by Django 4.2.28 on 2026-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_credit_note_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Product photo (max 5MB, PNG/JPG/WEBP)', null=True, upload_to='items/'),
        ),
    ]
