# Generated by Django 4.2.28 on 2026-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Link to product page, Instagram, or external catalog', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Product photo (max 10MB, PNG/JPG/WEBP)', null=True, upload_to='items/'),
        ),
    ]
