# Generated by Django 4.2.28 on 2026-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_external_url_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditnote',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='source_document_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='True if created automatically by a platform integration'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Origin of this invoice: empty=manual, shopify, api, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='source_document_id',
            field=models.CharField(blank=True, default='', help_text='External document ID (e.g., Shopify order ID)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='salescreditnote',
            index=models.Index(fields=['company', 'source'], name='sales_sales_company_4c5221_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'source'], name='sales_sales_company_f6bab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('source__gt', '')), fields=('company', 'source', 'source_document_id'), name='uniq_source_doc_per_company_credit_note'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('source__gt', '')), fields=('company', 'source', 'source_document_id'), name='uniq_source_doc_per_company_invoice'),
        ),
    ]
