# Generated by Django 4.2.28 on 2026-05-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_source_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Allow sales of this item even when stock would go negative'),
        ),
    ]
