# Generated by Django 4.2.28 on 2026-05-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_platform_managed_locations'),
        ('sales', '0010_add_allow_negative_stock_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse this line ships from (defaults to company default)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouse'),
        ),
    ]
