# Generated by Django 4.2.28 on 2026-03-24 09:17

import backups.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manual'), ('RESTORE', 'Restore')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=backups.models.backup_upload_path)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('model_counts', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.backuprecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='backups_bac_company_bb1a96_idx'), models.Index(fields=['company', '-created_at'], name='backups_bac_company_abf7cc_idx')],
            },
        ),
    ]
