# Generated by Django 4.2.28 on 2026-03-13 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_add_company_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shop_domain', models.CharField(help_text='e.g. my-store.myshopify.com', max_length=255)),
                ('access_token', models.CharField(blank=True, help_text='Shopify Admin API access token (encrypted at rest in production).', max_length=255)),
                ('scopes', models.CharField(blank=True, help_text='Granted OAuth scopes, comma-separated.', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending OAuth'), ('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('webhooks_registered', models.BooleanField(default=False)),
                ('source_system_id', models.IntegerField(blank=True, help_text='FK to edim.SourceSystem for this store.', null=True)),
                ('oauth_nonce', models.CharField(blank=True, max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_store', to='accounts.company')),
            ],
            options={
                'db_table': 'shopify_store',
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_order_id', models.BigIntegerField(db_index=True)),
                ('shopify_order_number', models.CharField(max_length=50)),
                ('shopify_order_name', models.CharField(blank=True, help_text='Display name like #1001', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('financial_status', models.CharField(blank=True, max_length=30)),
                ('gateway', models.CharField(blank=True, max_length=100)),
                ('shopify_created_at', models.DateTimeField()),
                ('order_date', models.DateField(help_text='Date used for journal entry')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, help_text='BusinessEvent ID created for this order.', null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, help_text='JournalEntry public_id created by projection.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_orders', to='accounts.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_order',
                'ordering': ['-shopify_created_at'],
                'unique_together': {('company', 'shopify_order_id')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_refund_id', models.BigIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('shopify_created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_refunds', to='accounts.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='shopify_connector.shopifyorder')),
            ],
            options={
                'db_table': 'shopify_refund',
                'unique_together': {('company', 'shopify_refund_id')},
            },
        ),
    ]
