# Generated by Django 4.2.25 on 2026-03-15 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('shopify_connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_payout_id', models.BigIntegerField(db_index=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total amount before fees', max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Processing fees deducted by Shopify', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount deposited to bank (gross - fees)', max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('shopify_status', models.CharField(blank=True, max_length=30)),
                ('payout_date', models.DateField(help_text='Date used for journal entry')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, help_text='BusinessEvent ID created for this payout.', null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, help_text='JournalEntry public_id created by projection.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_payouts', to='accounts.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_payout',
                'ordering': ['-payout_date'],
                'unique_together': {('company', 'shopify_payout_id')},
            },
        ),
    ]
