# Generated by Django 4.2.28 on 2026-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0002_add_shopify_payout_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifypayout',
            name='adjustments_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='shopifypayout',
            name='adjustments_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='shopifypayout',
            name='charges_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='shopifypayout',
            name='charges_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='shopifypayout',
            name='refunds_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='shopifypayout',
            name='refunds_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
