# Generated by Django 4.2.28 on 2026-03-15 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('shopify_connector', '0003_add_payout_fee_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_fulfillment_id', models.BigIntegerField(db_index=True)),
                ('shopify_order_id', models.BigIntegerField()),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('tracking_company', models.CharField(blank=True, max_length=255)),
                ('shopify_status', models.CharField(blank=True, help_text='Shopify fulfillment status (success, cancelled, error)', max_length=30)),
                ('shopify_created_at', models.DateTimeField()),
                ('total_cogs', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of goods for this fulfillment', max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('matched_items', models.IntegerField(default=0, help_text='Number of line items matched to inventory Items')),
                ('total_items', models.IntegerField(default=0, help_text='Total number of line items in the fulfillment')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('PARTIAL', 'Partially Matched'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, help_text='BusinessEvent ID created for this fulfillment.', null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, help_text='COGS JournalEntry public_id created by projection.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_fulfillments', to='accounts.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='shopify_connector.shopifyorder')),
            ],
            options={
                'db_table': 'shopify_fulfillment',
                'ordering': ['-shopify_created_at'],
                'unique_together': {('company', 'shopify_fulfillment_id')},
            },
        ),
    ]
