# Generated by Django 4.2.28 on 2026-03-15 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('shopify_connector', '0004_add_shopify_fulfillment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyPayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_transaction_id', models.BigIntegerField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('payout', 'Payout'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount of the transaction', max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee charged on this transaction', max_digits=18)),
                ('net', models.DecimalField(decimal_places=2, help_text='Net amount (amount - fee)', max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('source_order_id', models.BigIntegerField(blank=True, help_text='Shopify order ID this transaction relates to', null=True)),
                ('source_type', models.CharField(blank=True, help_text="Source type from Shopify (e.g. 'order', 'refund', 'adjustment')", max_length=30)),
                ('verified', models.BooleanField(default=False, help_text='Whether this transaction has been matched to a local order/refund')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this transaction was processed by Shopify', null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_payout_transactions', to='accounts.company')),
                ('local_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_transactions', to='shopify_connector.shopifyorder')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shopify_connector.shopifypayout')),
            ],
            options={
                'db_table': 'shopify_payout_transaction',
                'ordering': ['-processed_at'],
                'unique_together': {('company', 'shopify_transaction_id')},
            },
        ),
    ]
