# Generated by Django 4.2.28 on 2026-03-15 22:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('shopify_connector', '0005_add_payout_transaction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shopify_dispute_id', models.BigIntegerField(db_index=True)),
                ('shopify_order_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Disputed amount', max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Chargeback fee charged by payment processor', max_digits=18)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('shopify_dispute_status', models.CharField(blank=True, choices=[('needs_response', 'Needs Response'), ('under_review', 'Under Review'), ('charge_refunded', 'Charge Refunded'), ('accepted', 'Accepted'), ('won', 'Won'), ('lost', 'Lost')], max_length=30)),
                ('evidence_due_by', models.DateTimeField(blank=True, null=True)),
                ('finalized_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('WON', 'Won'), ('LOST', 'Lost'), ('ERROR', 'Error')], default='RECEIVED', max_length=20)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_disputes', to='accounts.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='shopify_connector.shopifyorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_dispute',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'shopify_dispute_id')},
            },
        ),
    ]
