# Generated by Django 4.2.28 on 2026-03-15 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('shopify_connector', '0006_add_shopify_dispute_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_stores', to='accounts.company'),
        ),
        migrations.AddConstraint(
            model_name='shopifystore',
            constraint=models.UniqueConstraint(fields=('company', 'shop_domain'), name='uniq_company_shop_domain'),
        ),
    ]
