# Generated by Django 4.2.28 on 2026-03-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_add_bank_reconciliation'),
        ('accounts', '0022_add_notification_model'),
        ('sales', '0004_salesinvoice_amount_paid_receiptallocation_and_more'),
        ('shopify_connector', '0007_multi_store_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='default_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Default COGS expense account for auto-created Items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Default inventory asset account for auto-created Items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='product_sync_enabled',
            field=models.BooleanField(default=False, help_text='Auto-create Items from Shopify product webhooks'),
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(db_index=True)),
                ('shopify_variant_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('variant_title', models.CharField(blank=True, default='', max_length=500)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=255)),
                ('shopify_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('shopify_inventory_item_id', models.BigIntegerField(blank=True, help_text='Shopify inventory_item_id for future inventory level sync', null=True)),
                ('auto_created', models.BooleanField(default=False, help_text='Whether the linked Item was auto-created by sync')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_products', to='accounts.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_variants', to='sales.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_product',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'shopify_variant_id')},
            },
        ),
    ]
