# Generated by Django 4.2.28 on 2026-04-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_add_fx_rounding_account_role'),
        ('sales', '0009_add_source_tracking_fields'),
        ('shopify_connector', '0009_unique_active_shop_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='default_customer',
            field=models.ForeignKey(blank=True, help_text='Customer record used for auto-created SalesInvoices from this store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.customer'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='default_posting_profile',
            field=models.ForeignKey(blank=True, help_text='PostingProfile (Shopify Clearing as control account) for auto-invoices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.postingprofile'),
        ),
    ]
