# Generated by Django 4.2.28 on 2026-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0010_add_module_routing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PENDING_CAPTURE', 'Pending Capture'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='RECEIVED', max_length=20),
        ),
    ]
