# Generated by Django 4.2.28 on 2026-05-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0013_add_gdpr_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifystore',
            name='webhooks_registered',
        ),
    ]
