# Generated by Django 4.2.28 on 2026-06-05 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_tos_consent_fields'),
        ('shopify_connector', '0015_a122_rotating_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingShopifyInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Short TTL (~30 min) — the merchant must finish login + company select before this.')),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_shopify_installs', to='accounts.company')),
            ],
            options={
                'db_table': 'shopify_pending_install',
                'indexes': [models.Index(fields=['expires_at'], name='shopify_pending_exp_idx')],
            },
        ),
    ]
