# Generated by Django 4.2.25 on 2026-06-23 07:26
#
# A47: the AlterFields widen the credential columns from varchar(255) to TEXT
# (Fernet ciphertext is larger than the plaintext) AND swap them to
# EncryptedTextField. The RunPython then encrypts any pre-existing plaintext
# rows in place. It uses RAW SQL on purpose — reading via the ORM would let
# EncryptedTextField.from_db_value pass plaintext through transparently, hiding
# whether a row is already encrypted; raw reads see the true stored bytes, so
# the is_encrypted() guard makes the backfill idempotent / re-runnable.

from django.db import migrations

import nxentra_backend.crypto

# (app_label, model_name, [credential field names]) to encrypt in place.
_TARGETS = [
    ("shopify_connector", "ShopifyStore", ["access_token", "refresh_token"]),
    ("shopify_connector", "PendingShopifyInstall", ["access_token", "refresh_token"]),
]


def _rewrite(apps, schema_editor, transform):
    from accounts.rls import rls_bypass

    conn = schema_editor.connection
    # rls_bypass is a no-op on SQLite; on Postgres it guarantees the raw
    # SELECT/UPDATE see every tenant's rows even if RLS_BYPASS isn't already on.
    with rls_bypass(conn=conn):
        with conn.cursor() as cur:
            for app_label, model_name, field_names in _TARGETS:
                model = apps.get_model(app_label, model_name)
                table = model._meta.db_table
                pk_col = model._meta.pk.column
                for fname in field_names:
                    col = model._meta.get_field(fname).column
                    cur.execute(f'SELECT "{pk_col}", "{col}" FROM "{table}"')
                    for pk, value in cur.fetchall():
                        new_value = transform(value)
                        if new_value is not None and new_value != value:
                            cur.execute(
                                f'UPDATE "{table}" SET "{col}" = %s WHERE "{pk_col}" = %s',
                                [new_value, pk],
                            )


def encrypt_existing(apps, schema_editor):
    from nxentra_backend.crypto import encrypt_secret, is_encrypted

    def transform(value):
        if value and not is_encrypted(value):
            return encrypt_secret(value)
        return None  # empty / already-encrypted → skip

    _rewrite(apps, schema_editor, transform)


def decrypt_existing(apps, schema_editor):
    from nxentra_backend.crypto import decrypt_secret, is_encrypted

    def transform(value):
        if is_encrypted(value):
            return decrypt_secret(value)
        return None  # plaintext / empty → skip

    _rewrite(apps, schema_editor, transform)


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0016_b6_pending_shopify_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingshopifyinstall',
            name='access_token',
            field=nxentra_backend.crypto.EncryptedTextField(help_text='Encrypted at rest (A47).'),
        ),
        migrations.AlterField(
            model_name='pendingshopifyinstall',
            name='refresh_token',
            field=nxentra_backend.crypto.EncryptedTextField(blank=True, help_text='Encrypted at rest (A47).'),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='access_token',
            field=nxentra_backend.crypto.EncryptedTextField(blank=True, help_text='Shopify Admin API access token. Encrypted at rest (A47).'),
        ),
        migrations.AlterField(
            model_name='shopifystore',
            name='refresh_token',
            field=nxentra_backend.crypto.EncryptedTextField(blank=True, help_text='Shopify refresh token (shprt_*). Encrypted at rest (A47). Used to obtain a new access token before the current one expires. Empty for legacy non-expiring tokens issued before A122.'),
        ),
        migrations.RunPython(encrypt_existing, decrypt_existing),
    ]
