# Generated by Django 4.2.25 on 2026-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0017_alter_pendingshopifyinstall_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprrequest',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
