# Generated by Django 4.2.25 on 2026-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0018_gdprrequest_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyfulfillment',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('PARTIAL', 'Partially Matched'), ('COGS_PENDING', 'COGS Pending Collection'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='RECEIVED', max_length=20),
        ),
    ]
