# Generated by Django 4.2.25 on 2026-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0019_alter_shopifyfulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='needs_reauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
