# Generated by Django 4.2.28 on 2026-07-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0027_company_enable_arabic_fields'),
        ('shopify_connector', '0020_shopifystore_needs_reauth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_sub', models.CharField(help_text="Shopify user id from the session token 'sub' claim.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_bindings', to='accounts.companymembership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bindings', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_user_binding',
            },
        ),
        migrations.CreateModel(
            name='ShopifyLinkingNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.companymembership')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linking_nonces', to='shopify_connector.shopifystore')),
            ],
            options={
                'db_table': 'shopify_linking_nonce',
            },
        ),
        migrations.AddConstraint(
            model_name='shopifyuserbinding',
            constraint=models.UniqueConstraint(fields=('store', 'shopify_sub'), name='uniq_store_shopify_sub'),
        ),
        migrations.AddConstraint(
            model_name='shopifyuserbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store',), name='uniq_active_binding_per_store'),
        ),
    ]
