# Generated by Django 4.2.28 on 2026-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_connector', '0021_shopifyuserbinding_shopifylinkingnonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='shop_currency',
            field=models.CharField(blank=True, default='', help_text="Store's Shopify presentment/shop currency (ISO code), refreshed from Shopify.", max_length=3),
        ),
    ]
