# Generated by Django 4.2.28 on 2026-08-23 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_pilotprofileactivation'),
        ('shopify_connector', '0022_shopifystore_shop_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyRejectedEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('store_public_id', models.UUIDField(help_text="Immutable snapshot of the store's public_id at ingress.")),
                ('shop_domain', models.CharField(help_text='Immutable snapshot of the shop domain at ingress.', max_length=255)),
                ('resource_kind', models.CharField(choices=[('ORDER', 'Order'), ('REFUND', 'Refund')], max_length=10)),
                ('ingress_kind', models.CharField(choices=[('WEBHOOK', 'Webhook'), ('POLLER', 'Poller')], max_length=10)),
                ('source_topic', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('raw_body_b64', models.TextField(blank=True, default='')),
                ('payload_hash', models.CharField(max_length=64)),
                ('transport_hash', models.CharField(blank=True, default='', max_length=64)),
                ('rejection_code', models.CharField(choices=[('MALFORMED_JSON', 'Malformed JSON body'), ('MISSING_EXTERNAL_ID', 'Missing or untrustworthy external id'), ('MALFORMED_MONEY', 'Malformed money value'), ('MALFORMED_CURRENCY', 'Malformed currency'), ('MALFORMED_DATE', 'Malformed date'), ('MALFORMED_STRUCTURE', 'Malformed structure')], max_length=40)),
                ('rejection_message', models.TextField()),
                ('validation_errors', models.JSONField(default=list)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('last_delivery_id', models.CharField(blank=True, default='', max_length=128)),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_note', models.TextField(blank=True, default='')),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_target_public_id', models.UUIDField(blank=True, null=True)),
                ('redacted_at', models.DateTimeField(blank=True, null=True)),
                ('dedup_hash', models.CharField(help_text='sha256(company_id|store_public_id|resource_kind|payload_hash) — source identity, not interpretation.', max_length=64)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_rejected_evidence', to='accounts.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_evidence', to='shopify_connector.shopifystore')),
                ('superseded_by_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shopify_connector.shopifyorder')),
                ('superseded_by_refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shopify_connector.shopifyrefund')),
            ],
            options={
                'db_table': 'shopify_rejected_evidence',
                'ordering': ['-id'],
                'indexes': [models.Index(condition=models.Q(('acknowledged', False), ('superseded_at__isnull', True)), fields=['company', '-id'], name='idx_sre_open_queue'), models.Index(fields=['company', 'store', 'resource_kind', 'external_id'], name='idx_sre_healing_lookup')],
            },
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.UniqueConstraint(fields=('company', 'dedup_hash'), name='uniq_shopify_rejected_evidence'),
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.CheckConstraint(check=models.Q(('superseded_at__isnull', False), models.Q(('superseded_by_order__isnull', True), ('superseded_by_refund__isnull', True), ('superseded_target_public_id__isnull', True)), _connector='OR'), name='ck_sre_open_has_no_supersede'),
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.CheckConstraint(check=models.Q(('resource_kind', 'ORDER'), ('superseded_by_refund__isnull', False), _negated=True), name='ck_sre_order_not_by_refund'),
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.CheckConstraint(check=models.Q(('resource_kind', 'REFUND'), ('superseded_by_order__isnull', False), _negated=True), name='ck_sre_refund_not_by_order'),
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('superseded_by_order__isnull', True), ('superseded_by_refund__isnull', True)), models.Q(('superseded_at__isnull', False), ('superseded_target_public_id__isnull', False)), _connector='OR'), name='ck_sre_fk_implies_superseded'),
        ),
        migrations.AddConstraint(
            model_name='shopifyrejectedevidence',
            constraint=models.CheckConstraint(check=models.Q(('superseded_by_order__isnull', False), ('superseded_by_refund__isnull', False), _negated=True), name='ck_sre_single_supersede_fk'),
        ),
    ]
