# Generated by Django 4.2.28 on 2026-03-19 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0022_add_notification_model'),
        ('accounting', '0023_add_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(help_text="Display name, e.g. 'CIB Main Account'", max_length=255)),
                ('account_number_last4', models.CharField(blank=True, default='', help_text='Last 4 digits for display', max_length=4)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.company')),
                ('gl_account', models.ForeignKey(blank=True, help_text='Linked GL account from chart of accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('column_mapping', models.JSONField(default=dict, help_text='Mapping of CSV columns to our fields: {date: col_name, description: col_name, ...}')),
                ('error_message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='bank_connector.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connector_statements', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit (money in), Negative = debit (money out)', max_digits=18)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('EXCLUDED', 'Excluded')], default='UNMATCHED', max_length=20)),
                ('matched_content_type', models.CharField(blank=True, default='', help_text="e.g. 'stripe_payout', 'shopify_payout'", max_length=100)),
                ('matched_object_id', models.IntegerField(blank=True, help_text='ID of the matched payout record', null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_by', models.CharField(blank=True, default='', help_text="'auto' or 'manual'", max_length=20)),
                ('raw_data', models.JSONField(default=dict, help_text='Original CSV row data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_connector.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounts.company')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_connector.bankstatement')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['company', 'transaction_date'], name='bank_connec_company_c1beba_idx'), models.Index(fields=['company', 'status'], name='bank_connec_company_93a31f_idx')],
            },
        ),
    ]
