# Generated by Django 4.2.28 on 2026-03-24 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_add_notification_model'),
        ('bank_connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exception_type', models.CharField(choices=[('UNMATCHED_BANK_TX', 'Unmatched Bank Transaction'), ('UNMATCHED_PAYOUT', 'Unmatched Payout'), ('PAYOUT_DISCREPANCY', 'Payout Amount Discrepancy'), ('CLEARING_BALANCE', 'Clearing Balance Anomaly'), ('MISSING_JE', 'Missing Journal Entry'), ('FEE_VARIANCE', 'Fee Variance'), ('DUPLICATE_MATCH', 'Duplicate Match Detected')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('platform', models.CharField(blank=True, default='', help_text='Platform involved: shopify, stripe, or empty for bank-only', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount involved in the exception', max_digits=18, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exception_date', models.DateField(help_text='Date the exception relates to (e.g., payout date, transaction date)')),
                ('reference_type', models.CharField(blank=True, default='', help_text="e.g. 'bank_transaction', 'shopify_payout', 'stripe_payout'", max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the related record', null=True)),
                ('reference_label', models.CharField(blank=True, default='', help_text="Human-readable reference, e.g. 'Payout po_abc123'", max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured data about the exception (variance amounts, IDs, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recon_exceptions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_exceptions', to='accounts.company')),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recon_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='bank_connec_company_d9857a_idx'), models.Index(fields=['company', 'exception_type'], name='bank_connec_company_a17512_idx'), models.Index(fields=['company', 'severity', 'status'], name='bank_connec_company_04e479_idx'), models.Index(fields=['company', 'exception_date'], name='bank_connec_company_ece289_idx')],
            },
        ),
    ]
