# Generated by Django 4.2.25 on 2026-06-20 13:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0026_add_tos_consent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed (advisory)'), ('CONFIRMED', 'Confirmed'), ('NEEDS_REVIEW', 'Confirmed with unexplained difference'), ('REJECTED', 'Rejected'), ('UNMATCHED', 'Unmatched'), ('EXCLUDED', 'Excluded (operator marked out of scope)'), ('REVERSED', 'Reversed'), ('DISPUTED', 'Disputed')], default='CONFIRMED', max_length=20)),
                ('match_kind', models.CharField(blank=True, max_length=40)),
                ('confirmation_kind', models.CharField(blank=True, max_length=40)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bank_line_public_id', models.CharField(blank=True, max_length=64)),
                ('journal_line_public_id', models.CharField(blank=True, max_length=64)),
                ('additional_journal_line_public_ids', models.JSONField(blank=True, default=list)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('difference_reason', models.CharField(blank=True, max_length=40)),
                ('confirmed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('confirmed_by_email', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unmatched_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_links', to='accounts.company')),
            ],
            options={
                'db_table': 'reconciliation_link',
                'indexes': [models.Index(fields=['company', 'status'], name='reconciliat_company_9f62d4_idx'), models.Index(fields=['company', 'bank_line_public_id'], name='reconciliat_company_affd4d_idx'), models.Index(fields=['company', 'journal_line_public_id'], name='reconciliat_company_ab57fc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationlink',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uniq_recon_link_company_key'),
        ),
    ]
