# Generated by Django 4.2.25 on 2026-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliation_link_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationlink',
            name='clearance_je_public_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='provider_normalized_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationlink',
            name='settlement_batch_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='reconciliationlink',
            index=models.Index(fields=['company', 'settlement_batch_id'], name='reconciliat_company_0149ff_idx'),
        ),
    ]
