# Generated by Django 4.2.25 on 2026-01-14 18:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_company_options_alter_nxpermission_options_and_more'),
        ('events', '0001_initial'),
        ('accounting', '0005_accountanalysisdefault_analysisdimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance (positive = normal direction)', max_digits=18)),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all debits ever posted to this account', max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all credits ever posted to this account', max_digits=18)),
                ('entry_count', models.PositiveIntegerField(default=0, help_text='Number of journal entries affecting this account')),
                ('last_entry_date', models.DateField(blank=True, help_text='Date of most recent journal entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projected_balance', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='accounts.company')),
                ('last_event', models.ForeignKey(blank=True, help_text='Last event that updated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.businessevent')),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
            },
        ),
        migrations.CreateModel(
            name='PeriodAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('period_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('period_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_closed', models.BooleanField(default=False, help_text='Period is closed, no more postings allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_balances', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_balances', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Period Account Balance',
                'verbose_name_plural': 'Period Account Balances',
                'indexes': [models.Index(fields=['company', 'fiscal_year', 'period'], name='projections_company_088a52_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodaccountbalance',
            constraint=models.UniqueConstraint(fields=('company', 'account', 'fiscal_year', 'period'), name='uniq_period_account_balance'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['company', 'account'], name='projections_company_6f90e4_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['company', 'balance'], name='projections_company_1fa4c6_idx'),
        ),
    ]
