# Generated by Django 4.2.25 on 2026-01-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0002_projectionappliedevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectionappliedevent',
            new_name='projections_company_4718b7_idx',
            old_name='projections_proj_company_1c913f_idx',
        ),
    ]
