# Generated by Django 4.2.25 on 2026-01-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_public_id_fields'),
        ('projections', '0003_rename_projections_proj_company_1c913f_idx_projections_company_4718b7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'fiscal_year', 'period'], name='projections_company_90ae6d_idx'), models.Index(fields=['company', 'start_date', 'end_date'], name='projections_company_1d99f2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_year', 'period'), name='uniq_fiscal_period'),
        ),
    ]
