# Generated by Django 4.2.25 on 2026-02-14 10:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_company_allow_negative_inventory'),
        ('events', '0004_alter_businessevent_caused_by_user'),
        ('sales', '0002_item_average_cost_item_cogs_account_and_more'),
        ('inventory', '0001_initial'),
        ('projections', '0006_projectionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current quantity on hand', max_digits=18)),
                ('avg_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Current weighted average cost per unit', max_digits=18)),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total stock value = qty_on_hand * avg_cost', max_digits=18)),
                ('last_entry_date', models.DateField(blank=True, help_text='Date of most recent stock movement', null=True)),
                ('entry_count', models.PositiveIntegerField(default=0, help_text='Number of stock ledger entries affecting this balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Balance',
                'verbose_name_plural': 'Inventory Balances',
            },
        ),
        migrations.RenameIndex(
            model_name='projectionstatus',
            new_name='projections_company_6f183c_idx',
            old_name='projections_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='projectionstatus',
            new_name='projections_project_9ccff2_idx',
            old_name='projections_name_status_idx',
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='sales.item'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='last_event',
            field=models.ForeignKey(blank=True, help_text='Last event that updated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.businessevent'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'item'], name='projections_company_f92234_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'warehouse'], name='projections_company_100a43_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'item', 'warehouse'], name='projections_company_93d124_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'qty_on_hand'], name='projections_company_4900cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('company', 'item', 'warehouse'), name='uniq_inventory_balance'),
        ),
    ]
