# Generated by Django 4.2.25 on 2026-02-14 18:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_membership_voice_fields'),
        ('accounting', '0018_rename_accounting__company_sys_prot_idx_accounting__company_cc9005_idx'),
        ('events', '0004_alter_businessevent_caused_by_user'),
        ('projections', '0007_inventorybalance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance (positive = we owe vendor)', max_digits=18)),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all debits (payments, debit notes)', max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all credits (bills, credit notes from vendor)', max_digits=18)),
                ('transaction_count', models.PositiveIntegerField(default=0, help_text='Number of transactions affecting this vendor')),
                ('last_bill_date', models.DateField(blank=True, help_text='Date of most recent bill', null=True)),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of most recent payment made', null=True)),
                ('oldest_open_date', models.DateField(blank=True, help_text='Date of oldest unpaid item (for aging reports)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_balances', to='accounts.company')),
                ('last_event', models.ForeignKey(blank=True, help_text='Last event that updated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.businessevent')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projected_balance', to='accounting.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Balance',
                'verbose_name_plural': 'Vendor Balances',
                'indexes': [models.Index(fields=['company', 'vendor'], name='projections_company_678734_idx'), models.Index(fields=['company', 'balance'], name='projections_company_6a277c_idx'), models.Index(fields=['company', 'oldest_open_date'], name='projections_company_a5d79e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance (positive = owed to us)', max_digits=18)),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all debits (invoices, debit notes)', max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all credits (payments, credit notes)', max_digits=18)),
                ('transaction_count', models.PositiveIntegerField(default=0, help_text='Number of transactions affecting this customer')),
                ('last_invoice_date', models.DateField(blank=True, help_text='Date of most recent invoice', null=True)),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of most recent payment received', null=True)),
                ('oldest_open_date', models.DateField(blank=True, help_text='Date of oldest unpaid item (for aging reports)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_balances', to='accounts.company')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projected_balance', to='accounting.customer')),
                ('last_event', models.ForeignKey(blank=True, help_text='Last event that updated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.businessevent')),
            ],
            options={
                'verbose_name': 'Customer Balance',
                'verbose_name_plural': 'Customer Balances',
                'indexes': [models.Index(fields=['company', 'customer'], name='projections_company_98bedb_idx'), models.Index(fields=['company', 'balance'], name='projections_company_19edb5_idx'), models.Index(fields=['company', 'oldest_open_date'], name='projections_company_1e9fe8_idx')],
            },
        ),
    ]
