# Generated by Django 4.2.28 on 2026-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0009_fiscalyear_period_type_pab_last_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='projections_company_737904_idx',
            old_name='projections_company_fy_idx',
        ),
        migrations.RenameIndex(
            model_name='fiscalyear',
            new_name='projections_company_4be2c3_idx',
            old_name='projections_fy_status_idx',
        ),
        migrations.RenameIndex(
            model_name='periodaccountbalance',
            new_name='projections_company_077aed_idx',
            old_name='projections_company_acct_fy_idx',
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='period_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ADJUSTMENT', 'Adjustment')], default='NORMAL', help_text='NORMAL for periods 1-12, ADJUSTMENT for period 13', max_length=12),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='retained_earnings_entry_public_id',
            field=models.CharField(blank=True, default='', help_text='Public ID of the closing journal entry that transferred P&L to retained earnings', max_length=36),
        ),
    ]
