# Generated by Django 4.2.28 on 2026-03-11 03:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_add_dimension_kind_and_account_rules'),
        ('accounts', '0021_add_company_module'),
        ('projections', '0010_rename_projections_company_fy_idx_projections_company_737904_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_balances', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_balances', to='accounts.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.analysisdimension')),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.analysisdimensionvalue')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'dimension'], name='idx_dimbal_company_dim')],
            },
        ),
        migrations.AddConstraint(
            model_name='dimensionbalance',
            constraint=models.UniqueConstraint(fields=('company', 'dimension_value', 'account'), name='uniq_dimension_balance'),
        ),
    ]
